import { Product } from "./types";

export const categories = [
  "すべて",
  "テクノロジー",
  "ファッション",
  "食品・グルメ",
  "ホーム・生活",
  "ヘルス・ビューティー",
  "エンタメ・趣味",
];

export const productIcons: Record<string, string> = {
  "1": "Headphones",
  "2": "Shirt",
  "3": "Droplets",
  "4": "Radio",
  "5": "ShoppingBag",
  "6": "Cookie",
  "7": "BedDouble",
  "8": "Footprints",
  "9": "Palette",
  "10": "Pill",
  "11": "AlarmClock",
  "12": "CupSoda",
  "13": "Mouse",
  "14": "Circle",
  "15": "Glasses",
  "16": "PenTool",
  "17": "Flame",
  "18": "Eye",
};

export const products: Product[] = [
  {
    id: "1",
    name: "量子もつれワイヤレスイヤホン Pro",
    price: 12800,
    originalPrice: 19800,
    description: "量子もつれ技術を応用した次世代ワイヤレスイヤホン。音が耳に届く前に脳に直接伝わる（気がする）革新的なリスニング体験。ノイズキャンセリングではなく、ノイズ消滅機能搭載。バッテリーは量子状態のため、充電が必要かどうかは観測するまで不明。",
    category: "テクノロジー",
    image: "headphones",
    rating: 4.7,
    reviewCount: 2847,
    badge: "ベストセラー",
  },
  {
    id: "2",
    name: "透明マント（見えない生地使用）",
    price: 49800,
    originalPrice: 89800,
    description: "最先端の光学迷彩技術を用いた透明マント。着用すると周囲に溶け込み、存在感がゼロになります。※元々存在感が薄い方には効果が確認できない場合があります。洗濯機使用不可（どこにあるか分からなくなるため）。",
    category: "ファッション",
    image: "shirt",
    rating: 4.2,
    reviewCount: 1523,
  },
  {
    id: "3",
    name: "時間巻き戻しクリーム",
    price: 8900,
    originalPrice: 12900,
    description: "塗った部分の時間を5分だけ巻き戻すスキンケアクリーム。シワが消えるのではなく、シワができる前の状態に戻ります。※効果は主観的なものです。使用後に鏡を見ると若返った気がします。",
    category: "ヘルス・ビューティー",
    image: "droplets",
    rating: 4.5,
    reviewCount: 3201,
    badge: "Amazon's Choice",
  },
  {
    id: "4",
    name: "テレパシー翻訳機 v3.0",
    price: 34500,
    originalPrice: 45000,
    description: "相手の心の声をリアルタイムで翻訳。142カ国語対応。ペットの気持ちも翻訳可能（ただし猫の場合「ごはん」「寝たい」「触るな」の3パターンがほとんど）。会議中の本音が聞こえてしまうため、使用は自己責任で。",
    category: "テクノロジー",
    image: "radio",
    rating: 3.9,
    reviewCount: 892,
  },
  {
    id: "5",
    name: "無限ポケットトートバッグ",
    price: 15600,
    originalPrice: 22000,
    description: "四次元空間技術を応用した収納力無限大のトートバッグ。どれだけ物を入れても重さが変わらない画期的な設計。注意：一度入れたものを見つけ出すのに時間がかかる場合があります。ブラックホール発生時の保証は対象外です。",
    category: "ファッション",
    image: "shopping-bag",
    rating: 4.8,
    reviewCount: 5672,
    badge: "ベストセラー",
  },
  {
    id: "6",
    name: "記憶パン（味付き）",
    price: 2980,
    originalPrice: 3980,
    description: "食べると教科書の内容を一瞬で暗記できる夢のパン。チョコ味・メロンパン味・カレー味の3種セット。※暗記効果は食後30分で消えます。食べすぎると胃もたれと共に余計な知識が増えます。",
    category: "食品・グルメ",
    image: "cookie",
    rating: 4.1,
    reviewCount: 7823,
  },
  {
    id: "7",
    name: "AI搭載スマート枕",
    price: 29800,
    originalPrice: 39800,
    description: "睡眠中の夢をAIが分析し、最適な夢のストーリーを生成。好きな夢を選んで見ることができます。人気の夢ジャンル：「宝くじ当選」「空を飛ぶ」「締め切りに間に合う」。悪夢ブロック機能付き。",
    category: "ホーム・生活",
    image: "bed-double",
    rating: 4.6,
    reviewCount: 1245,
    badge: "新着",
  },
  {
    id: "8",
    name: "重力調整スリッパ",
    price: 6500,
    originalPrice: 9800,
    description: "足元の重力を微調整できるハイテクスリッパ。「ふわふわモード」で雲の上を歩いているような感覚に。「しっかりモード」で地に足のついた生活を。※月面モードでジャンプすると天井に頭をぶつける恐れがあります。",
    category: "ホーム・生活",
    image: "footprints",
    rating: 4.3,
    reviewCount: 2156,
  },
  {
    id: "9",
    name: "感情カメレオンTシャツ",
    price: 7800,
    originalPrice: 11800,
    description: "着用者の感情に合わせて色が変わるスマートTシャツ。嬉しい時は黄色、悲しい時は青、怒っている時は赤に変色。ポーカーフェイスが台無しになるため、ギャンブル時の着用は非推奨。",
    category: "ファッション",
    image: "palette",
    rating: 4.0,
    reviewCount: 1876,
  },
  {
    id: "10",
    name: "光合成サプリメント",
    price: 4200,
    originalPrice: 5800,
    description: "飲むだけで光合成ができるようになるサプリメント。日光浴するだけで栄養補給が完了。食費の大幅削減に。ただし、肌が若干緑がかる副作用あり。曇りの日はエネルギー不足になる可能性があります。",
    category: "ヘルス・ビューティー",
    image: "pill",
    rating: 3.8,
    reviewCount: 943,
  },
  {
    id: "11",
    name: "タイムトラベル目覚まし時計",
    price: 18900,
    originalPrice: 25000,
    description: "セットした時間に起きられなかった場合、5分前に自動で時間を巻き戻す目覚まし時計。理論上、永遠に寝坊しません。※時空の歪みにより、月曜日が2回来ることがあります。",
    category: "ホーム・生活",
    image: "alarm-clock",
    rating: 4.4,
    reviewCount: 3567,
    badge: "Amazon's Choice",
  },
  {
    id: "12",
    name: "どこでもドリンクバー水筒",
    price: 5400,
    originalPrice: 7200,
    description: "注いだ水が好きな飲み物に変わる魔法の水筒。100種類以上のドリンクに対応。人気メニュー：「完璧な温度のコーヒー」「永遠に炭酸が抜けないコーラ」「二日酔いが治るお味噌汁」。",
    category: "食品・グルメ",
    image: "cup-soda",
    rating: 4.9,
    reviewCount: 8901,
    badge: "ベストセラー",
  },
  {
    id: "13",
    name: "念力マウス（ワイヤレス）",
    price: 9900,
    originalPrice: 14800,
    description: "手を触れずに念力で操作できるマウス。思考だけでカーソルを動かせます。集中力が途切れるとカーソルが暴走する仕様。瞑想経験者推奨。電池不要（精神エネルギーで駆動）。",
    category: "テクノロジー",
    image: "mouse",
    rating: 3.7,
    reviewCount: 654,
  },
  {
    id: "14",
    name: "無限バブルラップ",
    price: 1980,
    originalPrice: 2980,
    description: "プチプチを潰しても自動で復活する永久プチプチ。ストレス解消に最適。1日8時間のプチプチで約200kcal消費（当社調べ）。静音モードと爽快サウンドモード切替可能。",
    category: "エンタメ・趣味",
    image: "circle",
    rating: 4.8,
    reviewCount: 12543,
    badge: "ベストセラー",
  },
  {
    id: "15",
    name: "平行世界ゴーグル",
    price: 42000,
    originalPrice: 59800,
    description: "別の平行世界の自分を覗き見できるVRゴーグル。「あの時違う選択をしていたら」が見える。人気の視聴コース：「告白していたら」「あの会社に入っていたら」「あの時もう一品頼んでいたら」。",
    category: "エンタメ・趣味",
    image: "glasses",
    rating: 4.5,
    reviewCount: 2234,
    badge: "新着",
  },
  {
    id: "16",
    name: "自動言い訳生成AIペン",
    price: 3900,
    originalPrice: 5900,
    description: "遅刻・忘れ物・提出遅れなど、あらゆるシーンに最適な言い訳を自動生成。信憑性スコア表示機能付き。上司・先生・パートナー向けにカスタマイズ可能。※使いすぎると信用を失います。",
    category: "テクノロジー",
    image: "pen-tool",
    rating: 4.1,
    reviewCount: 4521,
  },
  {
    id: "17",
    name: "永遠にアツアツ弁当箱",
    price: 7600,
    originalPrice: 9800,
    description: "量子断熱技術により、朝入れたおかずが永遠にアツアツ。逆に冷やしたいものは絶対に冷えない（アイスは入れないでください）。三段重ねで大容量。食洗機対応（ただし食洗機が熱くなりすぎる場合あり）。",
    category: "食品・グルメ",
    image: "flame",
    rating: 4.6,
    reviewCount: 3890,
  },
  {
    id: "18",
    name: "オーラ可視化メガネ",
    price: 22000,
    originalPrice: 32000,
    description: "人のオーラが色で見えるようになる特殊メガネ。気の合う相手は金色に、危険な相手は赤色に光る。合コンや面接で大活躍。※満員電車での使用はオーラ過多で目がチカチカします。",
    category: "ヘルス・ビューティー",
    image: "eye",
    rating: 4.3,
    reviewCount: 1678,
  },
];
