import {
  Headphones,
  Shirt,
  Droplets,
  Radio,
  ShoppingBag,
  Cookie,
  BedDouble,
  Footprints,
  Palette,
  Pill,
  AlarmClock,
  CupSoda,
  Mouse,
  Circle,
  Glasses,
  PenTool,
  Flame,
  Eye,
  Package,
  Smartphone,
  Laptop,
  Wifi,
  Cpu,
  Monitor,
  Camera,
  Mic,
  Speaker,
  Zap,
  Cloud,
  Rocket,
  Fingerprint,
  Scan,
  Lightbulb,
  Magnet,
  Telescope,
  Leaf,
  Brain,
  Crown,
  Diamond,
  Umbrella,
  Watch,
  Feather,
  Scissors,
  Star,
  Shield,
  Key,
  Wind,
  Snowflake,
  Sun,
  Lock,
  Gift,
  Thermometer,
  Moon,
  Compass,
  Apple,
  Fish,
  Coffee,
  Wine,
  Cherry,
  Cake,
  Pizza,
  Beer,
  Candy,
  Heart,
  Sparkles,
  Sofa,
  Lamp,
  Fan,
  Bell,
  Dog,
  Cat,
  Mountain,
  Music,
  Wrench,
  Target,
  Bike,
  Wand2,
  Cog,
  Flower2,
  Microscope,
  Bird,
  Bug,
  Guitar,
  Gamepad2,
  Trophy,
  Car,
  Tent,
} from "lucide-react";

const iconMap: Record<string, typeof Headphones> = {
  headphones: Headphones,
  shirt: Shirt,
  droplets: Droplets,
  radio: Radio,
  "shopping-bag": ShoppingBag,
  cookie: Cookie,
  "bed-double": BedDouble,
  footprints: Footprints,
  palette: Palette,
  pill: Pill,
  "alarm-clock": AlarmClock,
  "cup-soda": CupSoda,
  mouse: Mouse,
  circle: Circle,
  glasses: Glasses,
  "pen-tool": PenTool,
  flame: Flame,
  eye: Eye,
  smartphone: Smartphone,
  laptop: Laptop,
  wifi: Wifi,
  cpu: Cpu,
  monitor: Monitor,
  camera: Camera,
  mic: Mic,
  speaker: Speaker,
  zap: Zap,
  cloud: Cloud,
  rocket: Rocket,
  fingerprint: Fingerprint,
  scan: Scan,
  lightbulb: Lightbulb,
  magnet: Magnet,
  telescope: Telescope,
  brain: Brain,
  crown: Crown,
  diamond: Diamond,
  umbrella: Umbrella,
  watch: Watch,
  feather: Feather,
  scissors: Scissors,
  star: Star,
  shield: Shield,
  key: Key,
  wind: Wind,
  snowflake: Snowflake,
  sun: Sun,
  lock: Lock,
  gift: Gift,
  thermometer: Thermometer,
  moon: Moon,
  compass: Compass,
  leaf: Leaf,
  apple: Apple,
  fish: Fish,
  coffee: Coffee,
  wine: Wine,
  cherry: Cherry,
  cake: Cake,
  pizza: Pizza,
  beer: Beer,
  candy: Candy,
  heart: Heart,
  sparkles: Sparkles,
  sofa: Sofa,
  lamp: Lamp,
  fan: Fan,
  bell: Bell,
  dog: Dog,
  cat: Cat,
  mountain: Mountain,
  music: Music,
  wrench: Wrench,
  target: Target,
  bike: Bike,
  "wand-2": Wand2,
  cog: Cog,
  "flower-2": Flower2,
  microscope: Microscope,
  bird: Bird,
  bug: Bug,
  guitar: Guitar,
  "gamepad-2": Gamepad2,
  trophy: Trophy,
  car: Car,
  tent: Tent,
};

interface ProductIconProps {
  name: string;
  className?: string;
}

export function ProductIcon({ name, className = "w-12 h-12" }: ProductIconProps) {
  const Icon = iconMap[name] || Package;
  return <Icon className={`${className} text-primary`} />;
}
