import {
  Headphones, Shirt, Droplets, Radio, ShoppingBag, Cookie, BedDouble,
  Footprints, Palette, Pill, AlarmClock, CupSoda, Mouse, Glasses, PenTool,
  Flame, Eye, Smartphone, Laptop, Wifi, Cpu, Monitor, Camera, Mic, Speaker,
  Zap, Cloud, Rocket, Fingerprint, Scan, Lightbulb, Magnet, Telescope, Brain,
  Crown, Diamond, Umbrella, Watch, Feather, Scissors, Star, Shield, Key, Wind,
  Snowflake, Sun, Lock, Gift, Thermometer, Moon, Compass, Leaf, Apple, Fish,
  Coffee, Wine, Cherry, Cake, Pizza, Beer, Candy, Heart, Sparkles, Sofa, Lamp,
  Fan, Bell, Dog, Cat, Mountain, Music, Wrench, Target, Bike, Wand2, Cog,
  Flower2, Microscope, Bird, Bug, Guitar, Gamepad2, Trophy, Car, Tent,
  Keyboard, Circle, Package, Clock, User, Clapperboard, Bot, Navigation, Hand,
  Box, Ticket, Plane, Table2, PieChart, Bookmark, BookType, Languages, Tv2,
  Frame, CookingPot, Waves, DoorOpen, CloudSun, Armchair, Hammer, Luggage,
  type LucideIcon,
} from "lucide-react";

interface IconDef {
  kebab: string;
  pascal: string;
  component: LucideIcon;
}

export const iconRegistry: IconDef[] = [
  { kebab: "headphones", pascal: "Headphones", component: Headphones },
  { kebab: "shirt", pascal: "Shirt", component: Shirt },
  { kebab: "droplets", pascal: "Droplets", component: Droplets },
  { kebab: "radio", pascal: "Radio", component: Radio },
  { kebab: "shopping-bag", pascal: "ShoppingBag", component: ShoppingBag },
  { kebab: "cookie", pascal: "Cookie", component: Cookie },
  { kebab: "bed-double", pascal: "BedDouble", component: BedDouble },
  { kebab: "footprints", pascal: "Footprints", component: Footprints },
  { kebab: "palette", pascal: "Palette", component: Palette },
  { kebab: "pill", pascal: "Pill", component: Pill },
  { kebab: "alarm-clock", pascal: "AlarmClock", component: AlarmClock },
  { kebab: "cup-soda", pascal: "CupSoda", component: CupSoda },
  { kebab: "mouse", pascal: "Mouse", component: Mouse },
  { kebab: "glasses", pascal: "Glasses", component: Glasses },
  { kebab: "pen-tool", pascal: "PenTool", component: PenTool },
  { kebab: "flame", pascal: "Flame", component: Flame },
  { kebab: "eye", pascal: "Eye", component: Eye },
  { kebab: "smartphone", pascal: "Smartphone", component: Smartphone },
  { kebab: "laptop", pascal: "Laptop", component: Laptop },
  { kebab: "wifi", pascal: "Wifi", component: Wifi },
  { kebab: "cpu", pascal: "Cpu", component: Cpu },
  { kebab: "monitor", pascal: "Monitor", component: Monitor },
  { kebab: "camera", pascal: "Camera", component: Camera },
  { kebab: "mic", pascal: "Mic", component: Mic },
  { kebab: "speaker", pascal: "Speaker", component: Speaker },
  { kebab: "zap", pascal: "Zap", component: Zap },
  { kebab: "cloud", pascal: "Cloud", component: Cloud },
  { kebab: "rocket", pascal: "Rocket", component: Rocket },
  { kebab: "fingerprint", pascal: "Fingerprint", component: Fingerprint },
  { kebab: "scan", pascal: "Scan", component: Scan },
  { kebab: "lightbulb", pascal: "Lightbulb", component: Lightbulb },
  { kebab: "magnet", pascal: "Magnet", component: Magnet },
  { kebab: "telescope", pascal: "Telescope", component: Telescope },
  { kebab: "brain", pascal: "Brain", component: Brain },
  { kebab: "crown", pascal: "Crown", component: Crown },
  { kebab: "diamond", pascal: "Diamond", component: Diamond },
  { kebab: "umbrella", pascal: "Umbrella", component: Umbrella },
  { kebab: "watch", pascal: "Watch", component: Watch },
  { kebab: "feather", pascal: "Feather", component: Feather },
  { kebab: "scissors", pascal: "Scissors", component: Scissors },
  { kebab: "star", pascal: "Star", component: Star },
  { kebab: "shield", pascal: "Shield", component: Shield },
  { kebab: "key", pascal: "Key", component: Key },
  { kebab: "wind", pascal: "Wind", component: Wind },
  { kebab: "snowflake", pascal: "Snowflake", component: Snowflake },
  { kebab: "sun", pascal: "Sun", component: Sun },
  { kebab: "lock", pascal: "Lock", component: Lock },
  { kebab: "gift", pascal: "Gift", component: Gift },
  { kebab: "thermometer", pascal: "Thermometer", component: Thermometer },
  { kebab: "moon", pascal: "Moon", component: Moon },
  { kebab: "compass", pascal: "Compass", component: Compass },
  { kebab: "leaf", pascal: "Leaf", component: Leaf },
  { kebab: "apple", pascal: "Apple", component: Apple },
  { kebab: "fish", pascal: "Fish", component: Fish },
  { kebab: "coffee", pascal: "Coffee", component: Coffee },
  { kebab: "wine", pascal: "Wine", component: Wine },
  { kebab: "cherry", pascal: "Cherry", component: Cherry },
  { kebab: "cake", pascal: "Cake", component: Cake },
  { kebab: "pizza", pascal: "Pizza", component: Pizza },
  { kebab: "beer", pascal: "Beer", component: Beer },
  { kebab: "candy", pascal: "Candy", component: Candy },
  { kebab: "heart", pascal: "Heart", component: Heart },
  { kebab: "sparkles", pascal: "Sparkles", component: Sparkles },
  { kebab: "sofa", pascal: "Sofa", component: Sofa },
  { kebab: "lamp", pascal: "Lamp", component: Lamp },
  { kebab: "fan", pascal: "Fan", component: Fan },
  { kebab: "bell", pascal: "Bell", component: Bell },
  { kebab: "dog", pascal: "Dog", component: Dog },
  { kebab: "cat", pascal: "Cat", component: Cat },
  { kebab: "mountain", pascal: "Mountain", component: Mountain },
  { kebab: "music", pascal: "Music", component: Music },
  { kebab: "wrench", pascal: "Wrench", component: Wrench },
  { kebab: "target", pascal: "Target", component: Target },
  { kebab: "bike", pascal: "Bike", component: Bike },
  { kebab: "wand2", pascal: "Wand2", component: Wand2 },
  { kebab: "cog", pascal: "Cog", component: Cog },
  { kebab: "flower-2", pascal: "Flower2", component: Flower2 },
  { kebab: "microscope", pascal: "Microscope", component: Microscope },
  { kebab: "bird", pascal: "Bird", component: Bird },
  { kebab: "bug", pascal: "Bug", component: Bug },
  { kebab: "guitar", pascal: "Guitar", component: Guitar },
  { kebab: "gamepad-2", pascal: "Gamepad2", component: Gamepad2 },
  { kebab: "trophy", pascal: "Trophy", component: Trophy },
  { kebab: "car", pascal: "Car", component: Car },
  { kebab: "tent", pascal: "Tent", component: Tent },
  { kebab: "keyboard", pascal: "Keyboard", component: Keyboard },
  { kebab: "circle", pascal: "Circle", component: Circle },
  { kebab: "package", pascal: "Package", component: Package },
  { kebab: "clock", pascal: "Clock", component: Clock },
  { kebab: "user", pascal: "User", component: User },
  { kebab: "clapperboard", pascal: "Clapperboard", component: Clapperboard },
  { kebab: "bot", pascal: "Bot", component: Bot },
  { kebab: "navigation", pascal: "Navigation", component: Navigation },
  { kebab: "hand", pascal: "Hand", component: Hand },
  { kebab: "box", pascal: "Box", component: Box },
  { kebab: "ticket", pascal: "Ticket", component: Ticket },
  { kebab: "plane", pascal: "Plane", component: Plane },
  { kebab: "table-2", pascal: "Table2", component: Table2 },
  { kebab: "pie", pascal: "PieChart", component: PieChart },
  { kebab: "bookmark", pascal: "Bookmark", component: Bookmark },
  { kebab: "book-type", pascal: "BookType", component: BookType },
  { kebab: "languages", pascal: "Languages", component: Languages },
  { kebab: "tv-2", pascal: "Tv2", component: Tv2 },
  { kebab: "frame", pascal: "Frame", component: Frame },
  { kebab: "cooking-pot", pascal: "CookingPot", component: CookingPot },
  { kebab: "waves", pascal: "Waves", component: Waves },
  { kebab: "door-open", pascal: "DoorOpen", component: DoorOpen },
  { kebab: "cloud-sun", pascal: "CloudSun", component: CloudSun },
  { kebab: "armchair", pascal: "Armchair", component: Armchair },
  { kebab: "hammer", pascal: "Hammer", component: Hammer },
  { kebab: "luggage", pascal: "Luggage", component: Luggage },
];

export const ICON_OPTIONS: string[] = iconRegistry.map((d) => d.kebab);

export const iconMap: Record<string, LucideIcon> = {
  ...Object.fromEntries(iconRegistry.map((d) => [d.kebab, d.component])),
  // legacy aliases
  "wand-2": Wand2,
  horse: Package,
};

export const pascalToKebab: Record<string, string> = Object.fromEntries(
  iconRegistry.map((d) => [d.pascal, d.kebab]),
);
