import { Product } from "./types";

export const categories = [
  "すべて",
  "テクノロジー",
  "ファッション",
  "食品・グルメ",
  "ホーム・生活",
  "ヘルス・ビューティー",
  "エンタメ・趣味",
];

export const productIcons: Record<string, string> = {
  "1": "Headphones",
  "2": "Shirt",
  "3": "Droplets",
  "4": "Radio",
  "5": "ShoppingBag",
  "6": "Cookie",
  "7": "BedDouble",
  "8": "Footprints",
  "9": "Palette",
  "10": "Pill",
  "11": "AlarmClock",
  "12": "CupSoda",
  "13": "Mouse",
  "14": "Circle",
  "15": "Glasses",
  "16": "PenTool",
  "17": "Flame",
  "18": "Eye",
  "19": "Smartphone",
  "20": "Laptop",
  "21": "Wifi",
  "22": "Cpu",
  "23": "Monitor",
  "24": "Camera",
  "25": "Mic",
  "26": "Speaker",
  "27": "Zap",
  "28": "Cloud",
  "29": "Rocket",
  "30": "Fingerprint",
  "31": "Scan",
  "32": "Lightbulb",
  "33": "Magnet",
  "34": "Telescope",
  "35": "Brain",
  "36": "Crown",
  "37": "Diamond",
  "38": "Umbrella",
  "39": "Watch",
  "40": "Feather",
  "41": "Scissors",
  "42": "Star",
  "43": "Shield",
  "44": "Key",
  "45": "Wind",
  "46": "Snowflake",
  "47": "Sun",
  "48": "Lock",
  "49": "Gift",
  "50": "Thermometer",
  "51": "Moon",
  "52": "Compass",
  "53": "Apple",
  "54": "Fish",
  "55": "Coffee",
  "56": "Wine",
  "57": "Leaf",
  "58": "Cherry",
  "59": "Cake",
  "60": "Pizza",
  "61": "Beer",
  "62": "Candy",
  "63": "Flame",
  "64": "Cookie",
  "65": "CupSoda",
  "66": "Zap",
  "67": "Star",
  "68": "Heart",
  "69": "Sparkles",
  "70": "Sofa",
  "71": "Lamp",
  "72": "Fan",
  "73": "Bell",
  "74": "Dog",
  "75": "Cat",
  "76": "Cloud",
  "77": "Mountain",
  "78": "Music",
  "79": "Wrench",
  "80": "Target",
  "81": "Bike",
  "82": "Leaf",
  "83": "Lightbulb",
  "84": "Key",
  "85": "Wand2",
  "86": "Cog",
  "87": "Heart",
  "88": "Sparkles",
  "89": "Flower2",
  "90": "Microscope",
  "91": "Scissors",
  "92": "Sun",
  "93": "Moon",
  "94": "Thermometer",
  "95": "Shield",
  "96": "Brain",
  "97": "Diamond",
  "98": "Crown",
  "99": "Feather",
  "100": "Star",
  "101": "Leaf",
  "102": "Wind",
  "103": "Gamepad2",
  "104": "Trophy",
  "105": "Guitar",
  "106": "Music",
  "107": "Telescope",
  "108": "Circle",
  "109": "Bird",
  "110": "Bug",
  "111": "Car",
  "112": "Tent",
  "113": "Compass",
  "114": "Gift",
  "115": "Dog",
  "116": "Rocket",
  "117": "Camera",
  "118": "Monitor",
  "119": "Rocket",
  "120": "Brain",
  "121": "Gamepad2",
  "122": "Smartphone",
  "123": "Wifi",
  "124": "Cpu",
  "125": "Monitor",
  "126": "Camera",
  "127": "Lightbulb",
  "128": "Cloud",
  "129": "Scan",
  "130": "Zap",
  "131": "Fingerprint",
  "132": "Magnet",
  "133": "Laptop",
  "134": "Mouse",
  "135": "Speaker",
  "136": "Mic",
  "137": "Telescope",
  "138": "Shirt",
  "139": "Crown",
  "140": "Diamond",
  "141": "Umbrella",
  "142": "Watch",
  "143": "Feather",
  "144": "ShoppingBag",
  "145": "Glasses",
  "146": "Scissors",
  "147": "Star",
  "148": "Footprints",
  "149": "Palette",
  "150": "Lock",
  "151": "Key",
  "152": "Shield",
  "153": "Wind",
  "154": "Snowflake",
  "155": "Cookie",
  "156": "Cake",
  "157": "Pizza",
  "158": "Coffee",
  "159": "Beer",
  "160": "Apple",
  "161": "Fish",
  "162": "Cherry",
  "163": "Wine",
  "164": "CupSoda",
  "165": "Candy",
  "166": "Flame",
  "167": "Leaf",
  "168": "Sofa",
  "169": "BedDouble",
  "170": "Lamp",
  "171": "Fan",
  "172": "Bell",
  "173": "Wrench",
  "174": "Target",
  "175": "Cog",
  "176": "AlarmClock",
  "177": "Wand2",
  "178": "Dog",
  "179": "Cat",
  "180": "Mountain",
  "181": "Gift",
  "182": "Sun",
  "183": "Thermometer",
  "184": "Heart",
  "185": "Sparkles",
  "186": "Droplets",
  "187": "Pill",
  "188": "Eye",
  "189": "Flower2",
  "190": "Microscope",
  "191": "Moon",
  "192": "Compass",
  "193": "Bike",
  "194": "Bird",
  "195": "Bug",
  "196": "Guitar",
  "197": "Trophy",
  "198": "Car",
  "199": "Tent",
  "200": "Music",
  "201": "Circle",
  "202": "PenTool",
  "203": "Radio",
  "204": "Headphones",
  "205": "Rocket",
  "206": "Brain",
  "207": "Gamepad2",
  "208": "Smartphone",
  "209": "Crown",
  "210": "Diamond",
  "211": "Coffee",
  "212": "Pizza",
  "213": "Sofa",
  "214": "Lamp",
  "215": "Heart",
  "216": "Sparkles",
  "217": "Star",
  "218": "Gift",
};

export const products: Product[] = [
  {
    id: "1",
    name: "量子もつれワイヤレスイヤホン Pro",
    price: 12800,
    originalPrice: 19800,
    description: "量子もつれ技術を応用した次世代ワイヤレスイヤホン。音が耳に届く前に脳に直接伝わる（気がする）革新的なリスニング体験。ノイズキャンセリングではなく、ノイズ消滅機能搭載。バッテリーは量子状態のため、充電が必要かどうかは観測するまで不明。",
    category: "テクノロジー",
    image: "headphones",
    rating: 4.7,
    reviewCount: 2847,
    badge: "ベストセラー",
  },
  {
    id: "2",
    name: "透明マント（見えない生地使用）",
    price: 49800,
    originalPrice: 89800,
    description: "最先端の光学迷彩技術を用いた透明マント。着用すると周囲に溶け込み、存在感がゼロになります。※元々存在感が薄い方には効果が確認できない場合があります。洗濯機使用不可（どこにあるか分からなくなるため）。",
    category: "ファッション",
    image: "shirt",
    rating: 4.2,
    reviewCount: 1523,
  },
  {
    id: "3",
    name: "時間巻き戻しクリーム",
    price: 8900,
    originalPrice: 12900,
    description: "塗った部分の時間を5分だけ巻き戻すスキンケアクリーム。シワが消えるのではなく、シワができる前の状態に戻ります。※効果は主観的なものです。使用後に鏡を見ると若返った気がします。",
    category: "ヘルス・ビューティー",
    image: "droplets",
    rating: 4.5,
    reviewCount: 3201,
    badge: "カウカウ's Choice",
  },
  {
    id: "4",
    name: "テレパシー翻訳機 v3.0",
    price: 34500,
    originalPrice: 45000,
    description: "相手の心の声をリアルタイムで翻訳。142カ国語対応。ペットの気持ちも翻訳可能（ただし猫の場合「ごはん」「寝たい」「触るな」の3パターンがほとんど）。会議中の本音が聞こえてしまうため、使用は自己責任で。",
    category: "テクノロジー",
    image: "radio",
    rating: 3.9,
    reviewCount: 892,
  },
  {
    id: "5",
    name: "無限ポケットトートバッグ",
    price: 15600,
    originalPrice: 22000,
    description: "四次元空間技術を応用した収納力無限大のトートバッグ。どれだけ物を入れても重さが変わらない画期的な設計。注意：一度入れたものを見つけ出すのに時間がかかる場合があります。ブラックホール発生時の保証は対象外です。",
    category: "ファッション",
    image: "shopping-bag",
    rating: 4.8,
    reviewCount: 5672,
    badge: "ベストセラー",
  },
  {
    id: "6",
    name: "記憶パン（味付き）",
    price: 2980,
    originalPrice: 3980,
    description: "食べると教科書の内容を一瞬で暗記できる夢のパン。チョコ味・メロンパン味・カレー味の3種セット。※暗記効果は食後30分で消えます。食べすぎると胃もたれと共に余計な知識が増えます。",
    category: "食品・グルメ",
    image: "cookie",
    rating: 4.1,
    reviewCount: 7823,
  },
  {
    id: "7",
    name: "AI搭載スマート枕",
    price: 29800,
    originalPrice: 39800,
    description: "睡眠中の夢をAIが分析し、最適な夢のストーリーを生成。好きな夢を選んで見ることができます。人気の夢ジャンル：「宝くじ当選」「空を飛ぶ」「締め切りに間に合う」。悪夢ブロック機能付き。",
    category: "ホーム・生活",
    image: "bed-double",
    rating: 4.6,
    reviewCount: 1245,
    badge: "新着",
  },
  {
    id: "8",
    name: "重力調整スリッパ",
    price: 6500,
    originalPrice: 9800,
    description: "足元の重力を微調整できるハイテクスリッパ。「ふわふわモード」で雲の上を歩いているような感覚に。「しっかりモード」で地に足のついた生活を。※月面モードでジャンプすると天井に頭をぶつける恐れがあります。",
    category: "ホーム・生活",
    image: "footprints",
    rating: 4.3,
    reviewCount: 2156,
  },
  {
    id: "9",
    name: "感情カメレオンTシャツ",
    price: 7800,
    originalPrice: 11800,
    description: "着用者の感情に合わせて色が変わるスマートTシャツ。嬉しい時は黄色、悲しい時は青、怒っている時は赤に変色。ポーカーフェイスが台無しになるため、ギャンブル時の着用は非推奨。",
    category: "ファッション",
    image: "palette",
    rating: 4.0,
    reviewCount: 1876,
  },
  {
    id: "10",
    name: "光合成サプリメント",
    price: 4200,
    originalPrice: 5800,
    description: "飲むだけで光合成ができるようになるサプリメント。日光浴するだけで栄養補給が完了。食費の大幅削減に。ただし、肌が若干緑がかる副作用あり。曇りの日はエネルギー不足になる可能性があります。",
    category: "ヘルス・ビューティー",
    image: "pill",
    rating: 3.8,
    reviewCount: 943,
  },
  {
    id: "11",
    name: "タイムトラベル目覚まし時計",
    price: 18900,
    originalPrice: 25000,
    description: "セットした時間に起きられなかった場合、5分前に自動で時間を巻き戻す目覚まし時計。理論上、永遠に寝坊しません。※時空の歪みにより、月曜日が2回来ることがあります。",
    category: "ホーム・生活",
    image: "alarm-clock",
    rating: 4.4,
    reviewCount: 3567,
    badge: "カウカウ's Choice",
  },
  {
    id: "12",
    name: "どこでもドリンクバー水筒",
    price: 5400,
    originalPrice: 7200,
    description: "注いだ水が好きな飲み物に変わる魔法の水筒。100種類以上のドリンクに対応。人気メニュー：「完璧な温度のコーヒー」「永遠に炭酸が抜けないコーラ」「二日酔いが治るお味噌汁」。",
    category: "食品・グルメ",
    image: "cup-soda",
    rating: 4.9,
    reviewCount: 8901,
    badge: "ベストセラー",
  },
  {
    id: "13",
    name: "念力マウス（ワイヤレス）",
    price: 9900,
    originalPrice: 14800,
    description: "手を触れずに念力で操作できるマウス。思考だけでカーソルを動かせます。集中力が途切れるとカーソルが暴走する仕様。瞑想経験者推奨。電池不要（精神エネルギーで駆動）。",
    category: "テクノロジー",
    image: "mouse",
    rating: 3.7,
    reviewCount: 654,
  },
  {
    id: "14",
    name: "無限バブルラップ",
    price: 1980,
    originalPrice: 2980,
    description: "プチプチを潰しても自動で復活する永久プチプチ。ストレス解消に最適。1日8時間のプチプチで約200kcal消費（当社調べ）。静音モードと爽快サウンドモード切替可能。",
    category: "エンタメ・趣味",
    image: "circle",
    rating: 4.8,
    reviewCount: 12543,
    badge: "ベストセラー",
  },
  {
    id: "15",
    name: "平行世界ゴーグル",
    price: 42000,
    originalPrice: 59800,
    description: "別の平行世界の自分を覗き見できるVRゴーグル。「あの時違う選択をしていたら」が見える。人気の視聴コース：「告白していたら」「あの会社に入っていたら」「あの時もう一品頼んでいたら」。",
    category: "エンタメ・趣味",
    image: "glasses",
    rating: 4.5,
    reviewCount: 2234,
    badge: "新着",
  },
  {
    id: "16",
    name: "自動言い訳生成AIペン",
    price: 3900,
    originalPrice: 5900,
    description: "遅刻・忘れ物・提出遅れなど、あらゆるシーンに最適な言い訳を自動生成。信憑性スコア表示機能付き。上司・先生・パートナー向けにカスタマイズ可能。※使いすぎると信用を失います。",
    category: "テクノロジー",
    image: "pen-tool",
    rating: 4.1,
    reviewCount: 4521,
  },
  {
    id: "17",
    name: "永遠にアツアツ弁当箱",
    price: 7600,
    originalPrice: 9800,
    description: "量子断熱技術により、朝入れたおかずが永遠にアツアツ。逆に冷やしたいものは絶対に冷えない（アイスは入れないでください）。三段重ねで大容量。食洗機対応（ただし食洗機が熱くなりすぎる場合あり）。",
    category: "食品・グルメ",
    image: "flame",
    rating: 4.6,
    reviewCount: 3890,
  },
  {
    id: "18",
    name: "オーラ可視化メガネ",
    price: 22000,
    originalPrice: 32000,
    description: "人のオーラが色で見えるようになる特殊メガネ。気の合う相手は金色に、危険な相手は赤色に光る。合コンや面接で大活躍。※満員電車での使用はオーラ過多で目がチカチカします。",
    category: "ヘルス・ビューティー",
    image: "eye",
    rating: 4.3,
    reviewCount: 1678,
  },
  {
    id: "19",
    name: "AI搭載全自動トイレナビ",
    price: 89800,
    originalPrice: 128000,
    description: "AIがあなたの腸内環境をリアルタイム分析し、最適なトイレタイミングを予測。Googleマップ連携で最寄りのトイレまでナビゲーション。緊急度に応じて3段階のアラート機能搭載。通勤中の安心感が段違い。",
    category: "テクノロジー",
    image: "smartphone",
    rating: 4.6,
    reviewCount: 3421,
    badge: "新着",
  },
  {
    id: "20",
    name: "夢記録ノートPC",
    price: 67800,
    originalPrice: 98000,
    description: "睡眠中の夢を自動録画してくれるノートPC。朝起きたら夢が4K動画として保存されている。編集機能付きで、夢のダイジェスト版も作成可能。SNSへの夢シェア機能搭載（炎上注意）。",
    category: "テクノロジー",
    image: "laptop",
    rating: 4.3,
    reviewCount: 1892,
  },
  {
    id: "21",
    name: "テレパシーWi-Fiルーター",
    price: 45000,
    originalPrice: 65000,
    description: "脳波を直接Wi-Fi信号に変換する次世代ルーター。考えるだけでネット検索が可能。ただし邪念が多いと回線が混雑します。家族共有モードでは思考が筒抜けになるため、一人暮らし推奨。",
    category: "テクノロジー",
    image: "wifi",
    rating: 3.8,
    reviewCount: 762,
  },
  {
    id: "22",
    name: "感情演算プロセッサ",
    price: 29800,
    originalPrice: 42000,
    description: "人間の感情を数値化して演算処理するチップ。怒りは512MB、悲しみは1GB、恋愛感情は処理落ちの原因になります。オーバークロックすると感情が暴走するので冷却ファン必須。",
    category: "テクノロジー",
    image: "cpu",
    rating: 3.9,
    reviewCount: 534,
  },
  {
    id: "23",
    name: "未来予知ディスプレイ",
    price: 78000,
    originalPrice: 99800,
    description: "10分後の未来を映し出す4Kディスプレイ。株価予測には使えません（利用規約で禁止）。主な用途は「電車の遅延予知」と「上司の機嫌チェック」。予知がハズレた場合は全額返金（ただし未来の通貨で）。",
    category: "テクノロジー",
    image: "monitor",
    rating: 4.1,
    reviewCount: 1203,
    badge: "限定品",
  },
  {
    id: "24",
    name: "過去撮影タイムカメラ",
    price: 54000,
    originalPrice: 72000,
    description: "シャッターを切ると、その場所の過去の風景が撮影できるカメラ。昨日のランチを思い出したい時や、「あの時の顔」を記録したい時に便利。3日以上前の撮影にはプレミアムプラン加入が必要。",
    category: "テクノロジー",
    image: "camera",
    rating: 4.4,
    reviewCount: 2567,
  },
  {
    id: "25",
    name: "動物語リアルタイム翻訳マイク",
    price: 19800,
    originalPrice: 28000,
    description: "動物の鳴き声を人間の言葉にリアルタイム翻訳。犬語・猫語・鳥語・魚語（泡の音）対応。翻訳精度は犬95%、猫30%（猫は本心を隠すため）。金魚の場合「...」が多め。",
    category: "テクノロジー",
    image: "mic",
    rating: 4.7,
    reviewCount: 8934,
    badge: "ベストセラー",
  },
  {
    id: "26",
    name: "無音なのに聞こえるスピーカー",
    price: 15900,
    originalPrice: 21000,
    description: "音波ではなく脳波で音楽を届けるスピーカー。周囲には一切聞こえないのに自分だけ最高の音質。電車内でも映画館でも使い放題。副作用として時々他人の音楽が混線します。",
    category: "テクノロジー",
    image: "speaker",
    rating: 4.2,
    reviewCount: 3456,
  },
  {
    id: "27",
    name: "人体発電アダプター",
    price: 8900,
    originalPrice: 12800,
    description: "体温と運動エネルギーをUSB電力に変換するアダプター。1時間の散歩でスマホ30%充電可能。怒りのエネルギーが最も変換効率が高く、上司に怒られた日はモバイルバッテリー不要。",
    category: "テクノロジー",
    image: "zap",
    rating: 4.0,
    reviewCount: 1876,
  },
  {
    id: "28",
    name: "記憶クラウドストレージ",
    price: 39800,
    originalPrice: 55000,
    description: "人間の記憶をクラウドにバックアップできるデバイス。テスト前に教科書の記憶をアップロードし、試験中にダウンロード。容量無制限プランあり。※思い出したくない記憶の完全削除機能は有料。",
    category: "テクノロジー",
    image: "cloud",
    rating: 4.5,
    reviewCount: 5678,
    badge: "カウカウ's Choice",
  },
  {
    id: "29",
    name: "通勤用ポケットジェットパック",
    price: 98000,
    originalPrice: 148000,
    description: "折りたたみ式のポケットサイズジェットパック。満員電車とはさようなら。最高速度は時速80km、航続距離は15km。ただし飛行中の着信応答は法律で禁止されています。駐機場所に困る場合あり。",
    category: "テクノロジー",
    image: "rocket",
    rating: 4.8,
    reviewCount: 987,
    badge: "人気急上昇",
  },
  {
    id: "30",
    name: "分身ホログラム生成デバイス",
    price: 72000,
    originalPrice: 95000,
    description: "自分のホログラム分身を生成し、会議に代理出席させるデバイス。AIが過去の発言パターンを学習し、適切に相槌を打ちます。「それ、いいですね」の精度は99.8%。本体は自宅で寝ていてOK。",
    category: "テクノロジー",
    image: "fingerprint",
    rating: 4.3,
    reviewCount: 2341,
  },
  {
    id: "31",
    name: "脳内Google検索メガネ",
    price: 42000,
    originalPrice: 58000,
    description: "考えるだけで脳内でGoogle検索ができるスマートメガネ。検索結果が視界にオーバーレイ表示される。広告も表示されるが、プレミアム版で非表示可能。検索履歴は本人以外閲覧不可（重要）。",
    category: "テクノロジー",
    image: "scan",
    rating: 4.6,
    reviewCount: 6789,
  },
  {
    id: "32",
    name: "強制ひらめきヘルメット",
    price: 25000,
    originalPrice: 35000,
    description: "装着すると5分以内に必ずアイデアがひらめくヘルメット。脳の創造性領域を電気刺激で活性化。企画会議の救世主。ただしひらめくアイデアの質は保証されません。「透明な水」レベルの発想も含まれます。",
    category: "テクノロジー",
    image: "lightbulb",
    rating: 3.7,
    reviewCount: 1432,
  },
  {
    id: "33",
    name: "幸運引き寄せアンテナ",
    price: 14800,
    originalPrice: 19800,
    description: "幸運の電波を受信して引き寄せるポータブルアンテナ。装着すると信号が全部青になり、自販機で当たりが出やすくなる。効果は半径3m以内。不運な人の近くでは電波干渉が起きます。",
    category: "テクノロジー",
    image: "magnet",
    rating: 3.5,
    reviewCount: 432,
  },
  {
    id: "34",
    name: "異世界観測望遠鏡",
    price: 85000,
    originalPrice: 120000,
    description: "異世界の様子をリアルタイムで覗ける高性能望遠鏡。ファンタジー世界、SF世界、なぜか全員猫の世界など多数のチャンネルあり。視聴中に向こう側から見返されることがあるので注意。",
    category: "テクノロジー",
    image: "telescope",
    rating: 4.9,
    reviewCount: 345,
    badge: "限定品",
  },
  {
    id: "35",
    name: "AI搭載セカンドブレイン",
    price: 59800,
    originalPrice: 78000,
    description: "第二の脳として機能するAIデバイス。忘れたことを代わりに覚えてくれて、思い出せない名前も即座に教えてくれる。デメリットは、AI脳の方が賢くなりすぎて本体の脳が怠け始めること。",
    category: "テクノロジー",
    image: "brain",
    rating: 4.4,
    reviewCount: 2890,
  },
  {
    id: "36",
    name: "王族オーラ発生ティアラ",
    price: 35000,
    originalPrice: 49800,
    description: "装着した瞬間から王族のオーラを放つティアラ。周囲の人が自然とお辞儀をし始めます。スーパーのレジでも優先的に案内される効果あり。オーラレベルは3段階調整可能（男爵・伯爵・皇帝）。",
    category: "ファッション",
    image: "crown",
    rating: 4.2,
    reviewCount: 2345,
    badge: "人気急上昇",
  },
  {
    id: "37",
    name: "自己肯定感MAXネックレス",
    price: 18500,
    originalPrice: 25000,
    description: "着けるだけで自己肯定感が爆上がりするネックレス。鏡を見るたびに「今日もイケてる」と確信できる。プレゼン前に装着すると無敵モードに突入。外すと反動で自信がゼロになる場合あり。",
    category: "ファッション",
    image: "diamond",
    rating: 4.5,
    reviewCount: 5432,
  },
  {
    id: "38",
    name: "天候操作パラソル",
    price: 28000,
    originalPrice: 38000,
    description: "開くと半径5m以内の天気を自由に操作できる日傘。雨の日でも晴天、夏でも涼しい風が吹く。デートの日は常に快晴。※隣の人の上だけ雨を降らせるイタズラモードは利用規約違反です。",
    category: "ファッション",
    image: "umbrella",
    rating: 4.7,
    reviewCount: 3456,
    badge: "ベストセラー",
  },
  {
    id: "39",
    name: "時間停止腕時計",
    price: 99800,
    originalPrice: 150000,
    description: "ボタンを押すと周囲の時間が5秒間だけ止まる腕時計。遅刻寸前のダッシュ、テスト中のカンニング防止、食べ放題での追加注文に最適。1日3回まで使用可能。電池交換は4次元ショップのみ対応。",
    category: "ファッション",
    image: "watch",
    rating: 4.8,
    reviewCount: 876,
    badge: "限定品",
  },
  {
    id: "40",
    name: "重力無視フェザーコート",
    price: 55000,
    originalPrice: 78000,
    description: "着用者の体重を見かけ上ゼロにするフェザーコート。階段の上り下りが楽になり、ジャンプ力が3倍に。強風の日は飛ばされる危険があるため、おもりポケット標準装備。冬は暖かく夏は涼しい万能素材。",
    category: "ファッション",
    image: "feather",
    rating: 4.1,
    reviewCount: 1567,
  },
  {
    id: "41",
    name: "自動おしゃれ変身スーツ",
    price: 42000,
    originalPrice: 60000,
    description: "TPOに合わせて自動で最適なコーディネートに変身するスーツ。結婚式、面接、デート、葬式すべてに対応。AIが周囲のファッションレベルを分析し、常に一段上のおしゃれを実現。クリーニング不要。",
    category: "ファッション",
    image: "scissors",
    rating: 4.6,
    reviewCount: 4567,
  },
  {
    id: "42",
    name: "カリスマ性注入ブローチ",
    price: 12800,
    originalPrice: 18000,
    description: "胸に付けるとカリスマ性が300%アップするブローチ。会議で発言すると全員が賛同し、道を歩くとなぜかフォロワーが増える。カリスマレベルを上げすぎると教祖になってしまうので注意。",
    category: "ファッション",
    image: "star",
    rating: 4.0,
    reviewCount: 2345,
  },
  {
    id: "43",
    name: "空気読みバリアジャケット",
    price: 33000,
    originalPrice: 45000,
    description: "空気が読めない発言をしそうになると自動でブザーが鳴るジャケット。飲み会での失言防止に最適。「それ言わない方がいいですよ」と小声でアドバイスしてくれるAI搭載。既読スルー検知機能付き。",
    category: "ファッション",
    image: "shield",
    rating: 4.3,
    reviewCount: 6789,
    badge: "カウカウ's Choice",
  },
  {
    id: "44",
    name: "異次元ポケット付きジーンズ",
    price: 16800,
    originalPrice: 22000,
    description: "ポケットが四次元空間に繋がっているジーンズ。スマホ5台、ペットボトル3本、ノートPC1台が余裕で入る。ただし奥に入れすぎると取り出すのに探検が必要。稀にポケットから異世界の生物が出てくる。",
    category: "ファッション",
    image: "key",
    rating: 4.4,
    reviewCount: 7890,
  },
  {
    id: "45",
    name: "風をまとうシルクマフラー",
    price: 9800,
    originalPrice: 14000,
    description: "常にそよ風がなびく演出付きのマフラー。どんな無風の日でもドラマチックに髪とマフラーがなびく。扇風機いらず。風力は5段階調整。最大レベルだと台風並みの風が発生するので室内使用非推奨。",
    category: "ファッション",
    image: "wind",
    rating: 3.9,
    reviewCount: 1234,
  },
  {
    id: "46",
    name: "永久冷却クールジャケット",
    price: 24800,
    originalPrice: 34000,
    description: "体感温度を常に22℃に保つジャケット。真夏の炎天下でも涼しく過ごせる。冷却システムの排熱が周囲に放出されるため、隣の人がちょっと暑くなる仕様。南極では使用を控えてください。",
    category: "ファッション",
    image: "snowflake",
    rating: 4.5,
    reviewCount: 3456,
  },
  {
    id: "47",
    name: "自家発電ソーラーサンバイザー",
    price: 7800,
    originalPrice: 11000,
    description: "太陽光でスマホを充電できるサンバイザー。晴れの日は歩くだけでモバイルバッテリー不要。USB-C端子2口搭載。曇りの日は充電されないどころか、帽子自体が電力を消費して肌寒くなる。",
    category: "ファッション",
    image: "sun",
    rating: 3.8,
    reviewCount: 2345,
  },
  {
    id: "48",
    name: "プライバシー完全防御サングラス",
    price: 21000,
    originalPrice: 29800,
    description: "着用すると監視カメラに映らなくなるサングラス。顔認証も完全に無効化。SNSに勝手にタグ付けされる心配もゼロ。ただし友達に街で声をかけられても気づいてもらえない副作用あり。",
    category: "ファッション",
    image: "lock",
    rating: 4.2,
    reviewCount: 4567,
  },
  {
    id: "49",
    name: "サプライズ自動生成ハット",
    price: 5900,
    originalPrice: 8500,
    description: "被るたびに帽子の中からランダムなサプライズが飛び出すハット。花束、紙吹雪、小鳥、時々請求書。パーティーで大活躍。出てくるものは選べません。一度だけドラゴンが出てきた報告あり。",
    category: "ファッション",
    image: "gift",
    rating: 4.0,
    reviewCount: 3456,
  },
  {
    id: "50",
    name: "体温完全制御サーモインナー",
    price: 11800,
    originalPrice: 16000,
    description: "体温を0.1度単位で調整できるインナーウェア。風邪の時は37.5度に設定して正当に休める。サウナでも快適温度を維持。上司に「顔色悪いぞ」と言われた時のワンタッチ青ざめ機能搭載。",
    category: "ファッション",
    image: "thermometer",
    rating: 4.3,
    reviewCount: 2890,
  },
  {
    id: "51",
    name: "月光チャージイブニングドレス",
    price: 68000,
    originalPrice: 95000,
    description: "月の光を吸収して淡く光り輝くイブニングドレス。満月の夜は照明いらずの明るさ。新月の夜は完全に消灯して存在が消える。パーティーでの注目度は満月時に最大。洗濯は月光の下で干すだけ。",
    category: "ファッション",
    image: "moon",
    rating: 4.7,
    reviewCount: 567,
    badge: "新着",
  },
  {
    id: "52",
    name: "運命の人探知ブレスレット",
    price: 15800,
    originalPrice: 22000,
    description: "運命の相手が半径100m以内にいると振動するブレスレット。近づくほど振動が強くなる。ただし「運命の人」の定義がAI判定のため、前世の知り合いや来世のパートナーも反応する場合あり。",
    category: "ファッション",
    image: "compass",
    rating: 3.6,
    reviewCount: 8901,
  },
  {
    id: "53",
    name: "知恵の実アップルパイ",
    price: 3800,
    originalPrice: 5200,
    description: "一切れ食べるとIQが一時的に20ポイント上昇するアップルパイ。試験前に大人気。味は普通のアップルパイだが、食べた後に急にニュートンの気持ちがわかるようになる。効果は6時間。",
    category: "食品・グルメ",
    image: "apple",
    rating: 4.3,
    reviewCount: 5678,
  },
  {
    id: "54",
    name: "しゃべる寿司12貫セット",
    price: 12800,
    originalPrice: 18000,
    description: "ネタが自己紹介してくれる寿司セット。マグロは「大間出身です」、サーモンは「ノルウェーから来ました」と語りかけてくる。ワサビは「覚悟はできていますか」と警告してくれる。食べるのが少し罪悪感。",
    category: "食品・グルメ",
    image: "fish",
    rating: 4.8,
    reviewCount: 2345,
    badge: "ベストセラー",
  },
  {
    id: "55",
    name: "72時間覚醒エスプレッソ",
    price: 980,
    originalPrice: 1500,
    description: "一杯飲むと72時間眠れなくなる超濃縮エスプレッソ。締め切り前のクリエイターに大人気。3日目以降は幻覚が見えるようになるが、それがかえって創造性を刺激する（個人の感想です）。",
    category: "食品・グルメ",
    image: "coffee",
    rating: 3.9,
    reviewCount: 12345,
  },
  {
    id: "56",
    name: "真実の口ワイン",
    price: 8500,
    originalPrice: 12000,
    description: "飲むと嘘がつけなくなるワイン。飲み会の告白タイムが地獄に変わる魔のワイン。「正直に言うとその服似合ってない」「実は猫派です」など、言わなくていい真実が溢れ出る。解毒には水を3リットル。",
    category: "食品・グルメ",
    image: "wine",
    rating: 4.1,
    reviewCount: 4567,
  },
  {
    id: "57",
    name: "カロリーマイナス唐揚げ",
    price: 2480,
    originalPrice: 3500,
    description: "食べれば食べるほど痩せる夢の唐揚げ。消化にカロリーを大量消費する特殊衣を使用。1個食べるごとにマイナス50kcal。味は普通の唐揚げと同じ（むしろ美味しい）。食べ放題の概念を覆す革命的商品。",
    category: "食品・グルメ",
    image: "leaf",
    rating: 4.9,
    reviewCount: 14523,
    badge: "ベストセラー",
  },
  {
    id: "58",
    name: "タイムカプセル桜餅",
    price: 1800,
    originalPrice: 2500,
    description: "食べると5分間だけ任意の季節の記憶を追体験できる桜餅。春を食べれば満開の桜の下にいる気分に。冬味・夏味・秋味もあり。食べすぎると季節感が狂い、8月にコタツを出し始める副作用あり。",
    category: "食品・グルメ",
    image: "cherry",
    rating: 4.4,
    reviewCount: 3456,
  },
  {
    id: "59",
    name: "食べても太らないチーズケーキ",
    price: 4200,
    originalPrice: 5800,
    description: "異次元技術によりカロリーが全て平行世界に転送されるチーズケーキ。こちらの世界の自分は太らないが、どこかの世界の自分が太る。罪悪感は半分。味は濃厚で最高。毎日食べても体重維持。",
    category: "食品・グルメ",
    image: "cake",
    rating: 4.6,
    reviewCount: 8901,
  },
  {
    id: "60",
    name: "無限再生マルゲリータ",
    price: 5800,
    originalPrice: 7800,
    description: "食べた分だけ自動で再生するピザ。1枚買えば一生ピザが食べられる。再生速度は約30分/1スライス。味は毎回微妙に変化し、まれにデザートピザが再生される。箱から出すと再生が止まるので注意。",
    category: "食品・グルメ",
    image: "pizza",
    rating: 4.7,
    reviewCount: 6789,
    badge: "カウカウ's Choice",
  },
  {
    id: "61",
    name: "完全記憶消去ビール",
    price: 1200,
    originalPrice: 1800,
    description: "飲むと直前1時間の記憶だけを完全に消去するビール。嫌な会議の後に最適。味はクラフトビール級に美味しい。飲みすぎると朝起きて自分が誰か分からなくなる場合あり（一時的です、多分）。",
    category: "食品・グルメ",
    image: "beer",
    rating: 3.8,
    reviewCount: 5678,
  },
  {
    id: "62",
    name: "IQ+50 天才キャンディ",
    price: 500,
    originalPrice: 800,
    description: "1粒でIQが50ポイント上昇する魔法のキャンディ。効果は2時間。グレープ味。舐め終わると急に「さっきの自分天才だったな」と振り返る。受験生に爆売れ中。1日3粒まで（それ以上は宇宙の真理に到達する恐れ）。",
    category: "食品・グルメ",
    image: "candy",
    rating: 4.5,
    reviewCount: 13456,
  },
  {
    id: "63",
    name: "永遠に冷めない魔法のラーメン",
    price: 1980,
    originalPrice: 2800,
    description: "注文から3時間経っても熱々のラーメン。スープの温度が永遠に95度をキープ。のびないノンストレッチ麺採用。猫舌の人には地獄。氷を入れても30秒で蒸発する。冬のキャンプに最適。",
    category: "食品・グルメ",
    image: "flame",
    rating: 4.2,
    reviewCount: 7890,
  },
  {
    id: "64",
    name: "性格チェンジクッキー",
    price: 1500,
    originalPrice: 2200,
    description: "食べると30分間だけ性格が正反対になるクッキー。内向的な人は急にパリピに、明るい人は急に哲学者になる。合コン前に食べると別人のように社交的に。副作用で翌日筋肉痛（慣れない動きのため）。",
    category: "食品・グルメ",
    image: "cookie",
    rating: 4.0,
    reviewCount: 4567,
  },
  {
    id: "65",
    name: "透明人間になれるジュース",
    price: 2200,
    originalPrice: 3200,
    description: "飲むと15分間だけ透明人間になれるジュース。マスカット味で美味しい。透明になるのは体だけで服は透明にならないので、全裸で飲む必要がある（重要）。この矛盾が最大の弱点。",
    category: "食品・グルメ",
    image: "cup-soda",
    rating: 3.7,
    reviewCount: 6789,
  },
  {
    id: "66",
    name: "永久エナジードリンク",
    price: 3500,
    originalPrice: 4800,
    description: "一本飲むと永久にエネルギーが切れないドリンク。ただし止まれなくなる副作用あり。飲んだ人の平均歩数は1日50,000歩。座っていても貧乏ゆすりが止まらない。解除には専用の鎮静ドリンクが必要。",
    category: "食品・グルメ",
    image: "zap",
    rating: 3.6,
    reviewCount: 2345,
  },
  {
    id: "67",
    name: "ミシュラン100つ星カレー",
    price: 9800,
    originalPrice: 15000,
    description: "異世界のミシュランガイドで100つ星を獲得したカレー。一口食べると涙が止まらなくなるほど美味しい（辛さではなく感動で）。食べた人全員が「人生変わった」と証言。スプーンが勝手に口に向かう。",
    category: "食品・グルメ",
    image: "star",
    rating: 5.0,
    reviewCount: 1234,
    badge: "限定品",
  },
  {
    id: "68",
    name: "恋愛成就チョコレート",
    price: 2800,
    originalPrice: 4000,
    description: "好きな人に渡すと恋愛成就率が87%上昇するチョコレート。失敗した13%は「チョコが美味しすぎてチョコに恋した」パターン。ホワイトデーにお返しが届く確率は200%（なぜか2倍返し）。",
    category: "食品・グルメ",
    image: "heart",
    rating: 4.4,
    reviewCount: 9012,
  },
  {
    id: "69",
    name: "幸運MAX開運弁当",
    price: 3200,
    originalPrice: 4500,
    description: "食べるとその日一日の運勢が最高になる弁当。おかずの配置が風水に基づいており、梅干しの位置が北東を指している。食べた日に宝くじを買った人の当選率は通常の3倍（当社調べ、サンプル数3人）。",
    category: "食品・グルメ",
    image: "sparkles",
    rating: 4.1,
    reviewCount: 5678,
  },
  {
    id: "70",
    name: "テレポートソファ",
    price: 78000,
    originalPrice: 110000,
    description: "座った瞬間に任意の場所にテレポートするソファ。目的地はリモコンで設定。通勤時間ゼロを実現。ただしソファごと移動するため、移動先にソファを置くスペースが必要。帰りは別のソファが必要。",
    category: "ホーム・生活",
    image: "sofa",
    rating: 4.5,
    reviewCount: 1234,
    badge: "新着",
  },
  {
    id: "71",
    name: "願いが叶う魔法のランプ",
    price: 45000,
    originalPrice: 65000,
    description: "こするとAIジーニーが現れて願いを3つ叶えてくれるデスクランプ。ただし願いの実現方法がいちいち合理的。「お金持ちになりたい」→「転職サイトを開きました」。3つ使い切ったら充電で復活。",
    category: "ホーム・生活",
    image: "lamp",
    rating: 4.2,
    reviewCount: 3456,
  },
  {
    id: "72",
    name: "台風発生ミニ扇風機",
    price: 4800,
    originalPrice: 6800,
    description: "風力設定を「MAX」にすると室内に小型台風が発生する扇風機。書類は吹き飛び、猫は避難し、カーテンは踊る。「そよ風モード」なら安全。クーラーが壊れた時の最終手段として一家に一台。",
    category: "ホーム・生活",
    image: "fan",
    rating: 3.9,
    reviewCount: 5678,
  },
  {
    id: "73",
    name: "未来からの着信ベル",
    price: 15800,
    originalPrice: 22000,
    description: "24時間後の自分からの電話が着信するドアベル。明日の天気、株価、今日食べるべきランチを教えてくれる。ただし未来の自分がめんどくさがって出ないことが多い。留守電機能搭載。",
    category: "ホーム・生活",
    image: "bell",
    rating: 4.0,
    reviewCount: 2345,
  },
  {
    id: "74",
    name: "ペット心理翻訳首輪",
    price: 12500,
    originalPrice: 17000,
    description: "ペットの気持ちを字幕表示する首輪。犬の場合「散歩！散歩！散歩！」が95%。猫の場合「なんで見てるの」「触るな」「ごはんまだ？」の無限ループ。金魚に装着すると「...」のみ表示。",
    category: "ホーム・生活",
    image: "dog",
    rating: 4.7,
    reviewCount: 11234,
    badge: "ベストセラー",
  },
  {
    id: "75",
    name: "猫型全自動お掃除ロボット",
    price: 35800,
    originalPrice: 48000,
    description: "猫の形をしたお掃除ロボット。本物の猫と同じく、気が向いた時だけ掃除する。掃除しない時は日向ぼっこモードで充電。深夜3時に突然掃除を始める猫あるあるも完全再現。毛玉は吐きません。",
    category: "ホーム・生活",
    image: "cat",
    rating: 4.4,
    reviewCount: 7890,
  },
  {
    id: "76",
    name: "室内天気コントローラー",
    price: 52000,
    originalPrice: 72000,
    description: "部屋の中の天気を自由に設定できるスマートデバイス。リビングだけ晴天、寝室は小雨（睡眠用）、風呂場は常に霧。花粉の季節は室内だけ花粉ゼロ設定可能。隣の部屋に雨が漏れることがあります。",
    category: "ホーム・生活",
    image: "cloud",
    rating: 4.3,
    reviewCount: 2345,
  },
  {
    id: "77",
    name: "室内富士山ホログラム",
    price: 28000,
    originalPrice: 38000,
    description: "リビングに富士山の等比縮小ホログラムを投影するデバイス。季節に合わせて雪化粧も変化。ご来光モードで朝日も再現。登山シミュレーション機能付きで、ソファから富士登山気分が味わえる。",
    category: "ホーム・生活",
    image: "mountain",
    rating: 4.5,
    reviewCount: 1567,
  },
  {
    id: "78",
    name: "自動作曲キッチンタイマー",
    price: 6800,
    originalPrice: 9500,
    description: "料理の残り時間に合わせてオリジナル曲を生成するキッチンタイマー。パスタ8分なら壮大な交響曲、カップ麺3分ならポップソング。焦げた時は緊急サイレンの代わりにデスメタルが流れる。",
    category: "ホーム・生活",
    image: "music",
    rating: 4.1,
    reviewCount: 3456,
  },
  {
    id: "79",
    name: "なんでも直せるAI工具箱",
    price: 19800,
    originalPrice: 28000,
    description: "壊れたものを入れると自動修理してくれるAI搭載工具箱。家電、家具、人間関係（は無理）に対応。修理時間はAIの気分次第。たまに「これは直さない方がいい」と哲学的な回答をすることもある。",
    category: "ホーム・生活",
    image: "wrench",
    rating: 4.2,
    reviewCount: 4567,
  },
  {
    id: "80",
    name: "ゴミ箱自動追尾システム",
    price: 14800,
    originalPrice: 19800,
    description: "投げたゴミを追いかけてキャッチするスマートゴミ箱。バスケットボール選手顔負けのキャッチ能力。ゴミを投げるとゴミ箱が高速移動して受け止める。成功率98%。失敗すると自分で拾いに行く。",
    category: "ホーム・生活",
    image: "target",
    rating: 4.6,
    reviewCount: 6789,
    badge: "人気急上昇",
  },
  {
    id: "81",
    name: "空飛ぶルンバ型掃除機",
    price: 42000,
    originalPrice: 58000,
    description: "床だけでなく天井や壁も掃除する空飛ぶ掃除機。反重力エンジン搭載で家中の埃を逃さない。ただし飛行中にペットを追いかけ回す習性があり、犬が怯える。夜間飛行モードは静音設計。",
    category: "ホーム・生活",
    image: "bike",
    rating: 4.3,
    reviewCount: 2345,
  },
  {
    id: "82",
    name: "光合成カーテン",
    price: 18500,
    originalPrice: 25000,
    description: "太陽光を吸収して夜に淡く光る光合成カーテン。電気代ゼロの間接照明。光合成で二酸化炭素を吸収し、酸素を放出するエコ設計。植物を育てるのが苦手な人の最終兵器。水やり不要。",
    category: "ホーム・生活",
    image: "leaf",
    rating: 4.4,
    reviewCount: 3456,
  },
  {
    id: "83",
    name: "アイデア強制発生デスクライト",
    price: 22000,
    originalPrice: 30000,
    description: "点灯すると半径2m以内にいる人のアイデアが止まらなくなるデスクライト。ブレスト会議で大活躍。ただし消灯後に「あのアイデア微妙だったな」と冷静になる率は80%。深夜に点けると眠れなくなる。",
    category: "ホーム・生活",
    image: "lightbulb",
    rating: 4.0,
    reviewCount: 1890,
  },
  {
    id: "84",
    name: "忘れ物テレポートキーホルダー",
    price: 7800,
    originalPrice: 11000,
    description: "忘れ物をした時にボタンを押すと、忘れた物が目の前にテレポートしてくるキーホルダー。ただしテレポートされるのは「最後に忘れた物」だけ。3つ忘れたら3回押す必要あり。鍵を忘れた時にこれも忘れがち。",
    category: "ホーム・生活",
    image: "key",
    rating: 4.1,
    reviewCount: 5678,
  },
  {
    id: "85",
    name: "魔法の自動掃除ステッキ",
    price: 16800,
    originalPrice: 23000,
    description: "振るだけで部屋が片付く魔法のステッキ。掃除・整理整頓・模様替えまで対応。ただし「片付ける」の定義がAI独自で、時々全てを押入れに詰め込む。魔法エフェクト（キラキラ）付き。",
    category: "ホーム・生活",
    image: "wand-2",
    rating: 4.5,
    reviewCount: 4567,
  },
  {
    id: "86",
    name: "全自動家事コンプリートロボ",
    price: 98000,
    originalPrice: 138000,
    description: "料理・掃除・洗濯・アイロンがけを完全自動化するロボット。さらに「お帰りなさい」「お疲れ様です」の声かけ機能付き。唯一できないのは「話を聞いてほしい時の相槌」。それは開発中。",
    category: "ホーム・生活",
    image: "cog",
    rating: 4.8,
    reviewCount: 890,
    badge: "新着",
  },
  {
    id: "87",
    name: "恋愛体質改善パッチ",
    price: 4800,
    originalPrice: 6800,
    description: "貼るだけでフェロモン分泌量が500%アップする恋愛パッチ。モテ期が強制的に到来。効果が強すぎてストーカーされる可能性があるため、使用量注意。犬にもモテるようになる副作用あり。",
    category: "ヘルス・ビューティー",
    image: "heart",
    rating: 4.1,
    reviewCount: 6789,
  },
  {
    id: "88",
    name: "美肌光線フェイスマスク",
    price: 15800,
    originalPrice: 22000,
    description: "装着すると顔面に美肌光線を照射するハイテクマスク。10分でエステ3回分の効果。使用中の見た目はSF映画のヴィランだが、外した後の美肌は映画スターレベル。男女兼用。夜間使用推奨。",
    category: "ヘルス・ビューティー",
    image: "sparkles",
    rating: 4.6,
    reviewCount: 4567,
    badge: "カウカウ's Choice",
  },
  {
    id: "89",
    name: "花粉症完全消滅スプレー",
    price: 2980,
    originalPrice: 4200,
    description: "ワンプッシュで半径10m以内の花粉を完全消滅させるスプレー。春が来るのが待ち遠しくなる革命的商品。花粉だけでなく、花粉症の人の涙と鼻水も止まる。1本で約100回使用可能。花も消える場合あり。",
    category: "ヘルス・ビューティー",
    image: "flower-2",
    rating: 4.8,
    reviewCount: 12345,
    badge: "ベストセラー",
  },
  {
    id: "90",
    name: "細胞レベル若返りクリーム",
    price: 38000,
    originalPrice: 55000,
    description: "塗った部分の細胞が若返りを開始するクリーム。顕微鏡で見ると細胞が踊っている。1週間で見た目年齢マイナス5歳。使いすぎると赤ちゃんに戻ってしまう恐れがあるため、用量厳守。",
    category: "ヘルス・ビューティー",
    image: "microscope",
    rating: 4.4,
    reviewCount: 2345,
  },
  {
    id: "91",
    name: "思い通りヘアスタイルジェル",
    price: 3200,
    originalPrice: 4500,
    description: "塗った後に理想の髪型を念じるだけで、その通りにスタイリングされるジェル。寝癖直しにも最適。ただし「かっこいい髪型」と漠然と念じるとAIが独自解釈してモヒカンになることがある。",
    category: "ヘルス・ビューティー",
    image: "scissors",
    rating: 4.0,
    reviewCount: 5678,
  },
  {
    id: "92",
    name: "ビタミン∞ 日焼け止めクリーム",
    price: 2500,
    originalPrice: 3500,
    description: "塗るとビタミンDを無限に生成する日焼け止め。日焼けしないのにビタミンは取れるという矛盾を実現。SPF∞で宇宙空間でも使用可能。塗りすぎると光合成が始まり、肌が微妙に緑がかる。",
    category: "ヘルス・ビューティー",
    image: "sun",
    rating: 4.3,
    reviewCount: 7890,
  },
  {
    id: "93",
    name: "快眠ムーンライトローション",
    price: 5600,
    originalPrice: 7800,
    description: "塗った瞬間から眠くなる月光パワーのローション。不眠症の人でも3分で熟睡。夢の質も向上し、8割の確率で良い夢を見れる。朝用と間違えて塗ると会議中に爆睡するので注意。ラベンダーの香り。",
    category: "ヘルス・ビューティー",
    image: "moon",
    rating: 4.7,
    reviewCount: 3456,
  },
  {
    id: "94",
    name: "永遠の平熱マスク",
    price: 1980,
    originalPrice: 2800,
    description: "装着すると体温が常に36.5度に保たれるマスク。風邪をひいても熱が出ないので出勤できる（ブラック企業御用達）。逆に仮病で休みたい時は「発熱モード」で37.8度に設定可能。",
    category: "ヘルス・ビューティー",
    image: "thermometer",
    rating: 3.8,
    reviewCount: 8901,
  },
  {
    id: "95",
    name: "ストレス完全防御アロマ",
    price: 6800,
    originalPrice: 9500,
    description: "この香りを嗅ぐとストレスが物理的にバウンドして消える。上司の小言、満員電車、SNSの炎上全てが「まぁいっか」になる。効果が切れた時の反動がすごいので、寝る前に追加プッシュ推奨。",
    category: "ヘルス・ビューティー",
    image: "shield",
    rating: 4.2,
    reviewCount: 4567,
  },
  {
    id: "96",
    name: "脳力MAXサプリメント",
    price: 7800,
    originalPrice: 11000,
    description: "飲むと脳の使用率が通常の10%から100%に上昇するサプリ。映画で見たやつが現実に。ただし100%になると哲学的疑問が止まらなくなり、「自分とは何か」を考えて1日が終わる。集中力は上がるが方向性は保証しない。",
    category: "ヘルス・ビューティー",
    image: "brain",
    rating: 3.9,
    reviewCount: 2345,
  },
  {
    id: "97",
    name: "ダイヤモンド肌ファンデーション",
    price: 12800,
    originalPrice: 18000,
    description: "塗ると肌がダイヤモンドのように輝くファンデーション。硬度も上がるため、蚊に刺されなくなる。光の加減で虹色に輝き、写真映えが異次元レベルに。落とすのにダイヤモンドカッターが必要（嘘です、普通のクレンジングで落ちます）。",
    category: "ヘルス・ビューティー",
    image: "diamond",
    rating: 4.5,
    reviewCount: 6789,
  },
  {
    id: "98",
    name: "小顔強制フォーミングティアラ",
    price: 9800,
    originalPrice: 14000,
    description: "装着すると顔のパーツが最適配置に自動調整されるティアラ。物理的に小顔にはならないが、周囲の人の認識を変える光学効果搭載。外すと「あれ、顔変わった？」と言われる。結婚式に最適。",
    category: "ヘルス・ビューティー",
    image: "crown",
    rating: 4.1,
    reviewCount: 3456,
  },
  {
    id: "99",
    name: "体重ゼロ感覚ダイエットベルト",
    price: 14800,
    originalPrice: 20000,
    description: "装着すると体が羽のように軽く感じるダイエットベルト。実際の体重は変わらないが、軽く感じるのでやる気が出る。やる気が出た結果、運動して本当に痩せる。プラシーボ効果の究極形。",
    category: "ヘルス・ビューティー",
    image: "feather",
    rating: 3.7,
    reviewCount: 5678,
  },
  {
    id: "100",
    name: "全身キラキラボディミスト",
    price: 3500,
    originalPrice: 4800,
    description: "吹きかけると全身がキラキラのオーラに包まれるボディミスト。主人公のオーラが出るため、街を歩くとBGMが聞こえてくる気がする。少女漫画の世界観が現実に。キラキラレベルは3段階調整可能。",
    category: "ヘルス・ビューティー",
    image: "star",
    rating: 4.3,
    reviewCount: 8901,
  },
  {
    id: "101",
    name: "オーガニック空気カプセル",
    price: 1200,
    originalPrice: 1800,
    description: "標高3000mの高原の空気を詰めたカプセル。飲むと5分間だけ高原の空気が肺を満たす。満員電車で息苦しい時に最適。森林浴味、海風味、温泉味の3種類。都会のコンクリートジャングルに潤いを。",
    category: "ヘルス・ビューティー",
    image: "leaf",
    rating: 3.8,
    reviewCount: 2345,
  },
  {
    id: "102",
    name: "瞬間リフレッシュ風シャワー",
    price: 8500,
    originalPrice: 12000,
    description: "ボタンを押すと全身に爽やかな風が吹き抜けるポータブルデバイス。水を使わない風だけのシャワー。汗も匂いも瞬間リセット。オフィスの昼休み後に最適。最大風力だとネクタイが飛んでいきます。",
    category: "ヘルス・ビューティー",
    image: "wind",
    rating: 4.4,
    reviewCount: 4567,
  },
  {
    id: "103",
    name: "現実世界RPGコントローラー",
    price: 32000,
    originalPrice: 45000,
    description: "現実世界をRPGのように操作できるコントローラー。経験値バー、HPゲージ、クエストリストが視界に表示される。日常のタスクがクエスト化され、掃除をするとゴールドが貯まる（使い道は不明）。",
    category: "エンタメ・趣味",
    image: "gamepad-2",
    rating: 4.6,
    reviewCount: 5678,
    badge: "人気急上昇",
  },
  {
    id: "104",
    name: "何でも優勝できるトロフィー",
    price: 8900,
    originalPrice: 12800,
    description: "部屋に置くとなぜか色々な大会で優勝するようになるトロフィー。町内会の運動会から社内コンペまで幅広く効果を発揮。ただし優勝するのは本当にギリギリで、毎回ドラマチックな展開になる。",
    category: "エンタメ・趣味",
    image: "trophy",
    rating: 4.2,
    reviewCount: 3456,
  },
  {
    id: "105",
    name: "プロ級自動演奏ギター",
    price: 45000,
    originalPrice: 62000,
    description: "持つだけでプロ級の演奏ができるギター。弾いてるフリをするだけでAIが自動演奏。歌に合わせて自動伴奏もしてくれる。路上ライブで投げ銭がもらえるレベル。ただしアンプラグドだとバレる。",
    category: "エンタメ・趣味",
    image: "guitar",
    rating: 4.5,
    reviewCount: 2345,
  },
  {
    id: "106",
    name: "カラオケ100点確定マイク",
    price: 12800,
    originalPrice: 18000,
    description: "歌うと自動的に音程・リズム・ビブラートを補正して100点を出すマイク。音痴でもプロ歌手レベルの歌声に。カラオケ大会で無敵だが、アカペラを求められた瞬間に真実が露呈する。",
    category: "エンタメ・趣味",
    image: "music",
    rating: 4.7,
    reviewCount: 8901,
    badge: "ベストセラー",
  },
  {
    id: "107",
    name: "推し活専用超望遠鏡",
    price: 28000,
    originalPrice: 38000,
    description: "推しの気配を感知し、自動でそちらを向く超望遠鏡。ライブ会場で推しのまばたきまで確認可能。推しが自分の方を見た瞬間にシャッターが切れる自動撮影機能搭載。※ストーカー行為への使用は禁止です。",
    category: "エンタメ・趣味",
    image: "telescope",
    rating: 4.3,
    reviewCount: 7890,
  },
  {
    id: "108",
    name: "運命操作イカサマサイコロ",
    price: 2400,
    originalPrice: 3500,
    description: "振ると必ず自分に有利な目が出るサイコロ。ボードゲームで無敵。ただしAI搭載で「ここは負けた方が面白い」と判断すると不利な目を出すこともある。サイコロの意思を尊重してください。",
    category: "エンタメ・趣味",
    image: "circle",
    rating: 3.9,
    reviewCount: 4567,
  },
  {
    id: "109",
    name: "鳥語マスターホイッスル",
    price: 5600,
    originalPrice: 7800,
    description: "吹くと鳥が集まってきて会話ができる笛。鳥たちに歌を教えたり、伝言を頼んだりできる。ハト・スズメ・カラスに対応。カラスは皮肉屋が多いので会話には覚悟が必要。鷹は有料DLCで対応予定。",
    category: "エンタメ・趣味",
    image: "bird",
    rating: 4.1,
    reviewCount: 2345,
  },
  {
    id: "110",
    name: "昆虫バトルアリーナセット",
    price: 7800,
    originalPrice: 11000,
    description: "昆虫たちがプロレスをするミニアリーナ。カブトムシvsクワガタの白熱バトルが楽しめる。実況AI付きで「おっと、ここでカブトムシが必殺技！」と盛り上げてくれる。昆虫へのダメージはゼロ設計。",
    category: "エンタメ・趣味",
    image: "bug",
    rating: 4.0,
    reviewCount: 3456,
  },
  {
    id: "111",
    name: "タイムトラベルミニカー",
    price: 15800,
    originalPrice: 22000,
    description: "ゼンマイを巻くと走りながら時空を超えるミニカー。過去に走っていくと歴史上の名車と並走してくれる。未来に走ると2050年のデザインの車になって戻ってくる。88マイル出す必要なし。",
    category: "エンタメ・趣味",
    image: "car",
    rating: 4.4,
    reviewCount: 1890,
  },
  {
    id: "112",
    name: "異世界キャンプフルセット",
    price: 52000,
    originalPrice: 72000,
    description: "テントを張ると異世界の景色が広がるキャンプセット。ファンタジーの森、SF都市、恐竜時代のジャングルなど20以上のテーマあり。焚き火はホログラムだが暖かい。虫は出ない（重要）。",
    category: "エンタメ・趣味",
    image: "tent",
    rating: 4.8,
    reviewCount: 987,
    badge: "新着",
  },
  {
    id: "113",
    name: "宝探し冒険コンパス",
    price: 9800,
    originalPrice: 13800,
    description: "近くに隠された「お宝」を探知するコンパス。公園や街中でお宝ハンティングが楽しめる。見つかるお宝は自販機の下の小銭、ベンチ裏のガチャガチャの景品など小さな幸せが中心。たまに本物の宝が見つかる（らしい）。",
    category: "エンタメ・趣味",
    image: "compass",
    rating: 4.2,
    reviewCount: 5678,
  },
  {
    id: "114",
    name: "開けるまで中身不明サプライズBOX",
    price: 3900,
    originalPrice: 5500,
    description: "開けるまで何が入っているか分からないサプライズボックス。中身はAIが「あなたが今最も必要としているもの」を選定。当たり：高級チョコ、ハズレ：モチベーションが上がるポエム。返品不可。",
    category: "エンタメ・趣味",
    image: "gift",
    rating: 3.6,
    reviewCount: 11234,
  },
  {
    id: "115",
    name: "ペット入れ替わり体験キット",
    price: 22000,
    originalPrice: 30000,
    description: "ペットと精神が入れ替わって30分間ペットの体を体験できるキット。犬の嗅覚の凄さ、猫の身体能力の高さを実感できる。帰ってこれなくなるケースは今のところゼロ件（公式発表）。",
    category: "エンタメ・趣味",
    image: "dog",
    rating: 4.5,
    reviewCount: 2345,
    badge: "限定品",
  },
  {
    id: "116",
    name: "自宅で宇宙旅行シミュレーター",
    price: 68000,
    originalPrice: 95000,
    description: "リビングにいながら宇宙旅行を体験できるシミュレーター。月面着陸、火星探索、ブラックホール観光ツアーが人気コース。無重力体験モードでは部屋の家具が浮くエフェクト付き（実際には浮きません）。",
    category: "エンタメ・趣味",
    image: "rocket",
    rating: 4.7,
    reviewCount: 1234,
  },
  {
    id: "117",
    name: "心霊写真撮影カメラ",
    price: 19800,
    originalPrice: 28000,
    description: "撮影すると高確率で心霊写真が撮れるカメラ。AIが自動で心霊現象を合成してくれる超ハイテク仕様。友達を驚かせるのに最適。「ガチ」と「エンタメ」モード切替可能。ホラー好きに大人気。",
    category: "エンタメ・趣味",
    image: "camera",
    rating: 4.0,
    reviewCount: 6789,
  },
  {
    id: "118",
    name: "平行世界ザッピングTV",
    price: 38000,
    originalPrice: 52000,
    description: "チャンネルを回すと別の平行世界のテレビ番組が映るTV。あちらの世界のニュース、バラエティ、ドラマが視聴可能。一番人気は「もしも恐竜が絶滅しなかったら」世界のNHK。受信料は不要（多分）。",
    category: "エンタメ・趣味",
    image: "monitor",
    rating: 4.6,
    reviewCount: 3456,
  },
  {
    id: "119",
    name: "宇宙通勤用パーソナルロケット",
    price: 98000,
    originalPrice: 148000,
    description: "片道15分で月面オフィスに到着するパーソナルロケット。折りたたみ式で駅のコインロッカーに収納可能。燃料は前日の夕食のカロリーを変換して使用。満腹時は火星まで届くが、ダイエット中は低軌道が限界。",
    category: "テクノロジー",
    image: "rocket",
    rating: 4.7,
    reviewCount: 876,
    badge: "新着",
  },
  {
    id: "120",
    name: "第三の脳みそ増設キット",
    price: 59800,
    originalPrice: 82000,
    description: "耳の後ろに装着する追加脳ユニット。マルチタスク能力が3倍になり、会議中にソシャゲをしながら議事録が取れる。副作用として3つの人格が生まれ、たまに脳内会議が始まる。多数決で意思決定。",
    category: "テクノロジー",
    image: "brain",
    rating: 4.2,
    reviewCount: 1543,
  },
  {
    id: "121",
    name: "現実バグ修正コントローラー",
    price: 45000,
    originalPrice: 65000,
    description: "現実世界のバグを発見して修正するコントローラー。「月曜日が来るバグ」は修正不可。「電車が遅れるバグ」は修正済みだが次のパッチで元に戻る。セーブ機能はないので人生はやり直せません。",
    category: "エンタメ・趣味",
    image: "gamepad-2",
    rating: 4.5,
    reviewCount: 3421,
    badge: "カウカウ's Choice",
  },
  {
    id: "122",
    name: "言い訳自動生成スマホケース",
    price: 4980,
    originalPrice: 7200,
    description: "遅刻しそうな時にスマホを振ると最適な言い訳をLINEで自動送信するケース。信憑性レベル調整機能付き。使いすぎると「またか」と学習されるため、月3回までの使用を推奨。GPSと連動して矛盾のない言い訳を生成。",
    category: "テクノロジー",
    image: "smartphone",
    rating: 3.9,
    reviewCount: 7654,
  },
  {
    id: "123",
    name: "隣人のWi-Fiお裾分けルーター",
    price: 12800,
    originalPrice: 18000,
    description: "近所のWi-Fiの余った帯域幅をおすそ分けしてもらえるルーター。お礼としてお隣さんに自動で手土産を注文する機能搭載。ギガが足りない時は町内会ネットワークが発動。回覧板もデジタル化。",
    category: "テクノロジー",
    image: "wifi",
    rating: 3.5,
    reviewCount: 432,
  },
  {
    id: "124",
    name: "感情過負荷冷却チップ",
    price: 22000,
    originalPrice: 32000,
    description: "恋愛や怒りで脳がオーバーヒートした時に冷却するチップ。告白前の心臓バクバクを即座に平常心に。ただし冷却しすぎると感情が凍結して何も感じなくなる「無」モードに入るので注意。解凍に2時間。",
    category: "テクノロジー",
    image: "cpu",
    rating: 4.0,
    reviewCount: 987,
  },
  {
    id: "125",
    name: "他人の画面が見えるモニター",
    price: 68000,
    originalPrice: 95000,
    description: "世界中のPCモニターの画面をランダムに表示するモニター。仕事中の他人の画面がリアルタイムで映る。98%の確率でExcelかSNS。残り2%は猫の動画。プライバシーは量子暗号化で安心（多分）。",
    category: "テクノロジー",
    image: "monitor",
    rating: 3.4,
    reviewCount: 234,
  },
  {
    id: "126",
    name: "食べ物が美味しく見えるカメラ",
    price: 35000,
    originalPrice: 48000,
    description: "どんな料理も高級レストラン級に撮影できるカメラ。コンビニ弁当がミシュラン三つ星に見える特殊フィルター搭載。いいね数が平均300%増加。ただし実物とのギャップで炎上するリスクあり。",
    category: "テクノロジー",
    image: "camera",
    rating: 4.6,
    reviewCount: 5678,
    badge: "ベストセラー",
  },
  {
    id: "127",
    name: "強制やる気スイッチ電球",
    price: 8900,
    originalPrice: 12000,
    description: "点灯するとやる気ホルモンが強制分泌される電球。勉強、掃除、確定申告が捗る。消すとやる気が消滅するので、終わるまで消さないこと。電気代は高いがやる気の値段と思えば安い。",
    category: "テクノロジー",
    image: "lightbulb",
    rating: 4.3,
    reviewCount: 4321,
  },
  {
    id: "128",
    name: "夢のサブスクリプションサービス端末",
    price: 15800,
    originalPrice: 22000,
    description: "月額制で好きな夢を選べるクラウド端末。人気ジャンル：異世界転生、推しとデート、上司が謝ってくる。無料プランは広告付きの夢（夢の途中でCMが入る）。解約を忘れると永遠に夢の中。",
    category: "テクノロジー",
    image: "cloud",
    rating: 4.4,
    reviewCount: 6543,
  },
  {
    id: "129",
    name: "顔面偏差値スキャナー",
    price: 19800,
    originalPrice: 28000,
    description: "顔をスキャンすると偏差値で数値化してくれるデバイス。ただしお世辞モードがデフォルトで、実力モードに切り替えると友情が壊れる可能性あり。美容整形シミュレーション機能も搭載。",
    category: "テクノロジー",
    image: "scan",
    rating: 3.2,
    reviewCount: 8765,
  },
  {
    id: "130",
    name: "静電気で充電するスマホ充電器",
    price: 6500,
    originalPrice: 9000,
    description: "冬のドアノブでバチッとくる静電気でスマホを充電する装置。セーター着用で充電効率300%UP。猫をなでると急速充電可能。夏場は使えない季節限定品だが、冬の電気代はゼロに。",
    category: "テクノロジー",
    image: "zap",
    rating: 3.8,
    reviewCount: 2345,
  },
  {
    id: "131",
    name: "嘘発見パスポートケース",
    price: 11000,
    originalPrice: 15800,
    description: "触れた人が嘘をついているかどうかが分かるパスポートケース。入国審査で無実を証明できる。ただし「お土産にお金を使いすぎた」という嘘は100%バレる。帰国後の家族との会話が緊張感に満ちる。",
    category: "テクノロジー",
    image: "fingerprint",
    rating: 4.1,
    reviewCount: 1234,
  },
  {
    id: "132",
    name: "モテ力磁石ブレスレット",
    price: 7800,
    originalPrice: 11000,
    description: "異性を引き寄せる磁力を発生するブレスレット。効果範囲は半径5m。ただし引き寄せ対象はランダムで、好みのタイプが来るとは限らない。S極モードでむしろ人を遠ざけることも可能。",
    category: "テクノロジー",
    image: "magnet",
    rating: 3.6,
    reviewCount: 9876,
  },
  {
    id: "133",
    name: "議事録が勝手に書けるPC",
    price: 88000,
    originalPrice: 120000,
    description: "会議中に勝手に議事録を書いてくれるノートPC。発言者の本音も括弧書きで追記する機能あり。「（早く終われ）」「（昼ごはん何にしよう）」などの注釈が入る。上司のPCには送信されない安心設計。",
    category: "テクノロジー",
    image: "laptop",
    rating: 4.8,
    reviewCount: 3456,
    badge: "ベストセラー",
  },
  {
    id: "134",
    name: "サボり検知回避マウス",
    price: 3980,
    originalPrice: 5500,
    description: "在宅勤務中にサボっていてもマウスが自動で動いてくれるデバイス。Teams/Slackのステータスを常に「オンライン」に維持。たまに意味ありげにファイルを開いてくれる演出付き。良心の呵責は別売り。",
    category: "テクノロジー",
    image: "mouse",
    rating: 4.9,
    reviewCount: 15678,
    badge: "ベストセラー",
  },
  {
    id: "135",
    name: "心の声ミュートスピーカー",
    price: 14800,
    originalPrice: 20000,
    description: "つい口に出そうな本音を自動検知してミュートするスピーカー。「ハゲ」「太った？」などの失言を未然に防止。会社の忘年会で効果を発揮。逆に本音を言いたい時は「暴露モード」に切替可能。",
    category: "テクノロジー",
    image: "speaker",
    rating: 4.3,
    reviewCount: 5432,
  },
  {
    id: "136",
    name: "説教自動短縮マイク",
    price: 9800,
    originalPrice: 13500,
    description: "上司の説教を自動で要約して3分以内に短縮するマイク。「つまり、気をつけろということですね」と自動で相槌も打つ。説教の長さに比例してポイントが貯まり、ポイントで有給が取れる。",
    category: "テクノロジー",
    image: "mic",
    rating: 4.5,
    reviewCount: 7890,
  },
  {
    id: "137",
    name: "推しの未来が見える望遠鏡",
    price: 32000,
    originalPrice: 45000,
    description: "推しの次のSNS投稿が事前に見える望遠鏡。新曲リリース、熱愛報道を誰よりも先にキャッチ。ただし見えた未来は変えられない。推しの引退が見えた時のメンタルサポートAI搭載。",
    category: "エンタメ・趣味",
    image: "telescope",
    rating: 4.1,
    reviewCount: 6543,
  },
  {
    id: "138",
    name: "着るだけで痩せて見えるTシャツ",
    price: 5980,
    originalPrice: 8500,
    description: "光学迷彩技術でウエストが-10cm細く見えるTシャツ。実際の体型は変わらないが周囲の認識を書き換える。正面からは細く見えるが横から見るとバレる。合コンでは常に正面を向いてください。",
    category: "ファッション",
    image: "shirt",
    rating: 4.0,
    reviewCount: 8765,
  },
  {
    id: "139",
    name: "社長に見えるネクタイ",
    price: 12800,
    originalPrice: 18000,
    description: "締めるだけで社長のオーラが出るネクタイ。部下がいなくても部下が集まってくる不思議なパワー。色は「年商10億ブルー」「上場ゴールド」「倒産寸前レッド」の3色展開。最も売れているのはレッド。",
    category: "ファッション",
    image: "crown",
    rating: 4.2,
    reviewCount: 3456,
  },
  {
    id: "140",
    name: "自己肯定感ダイヤピアス",
    price: 24800,
    originalPrice: 35000,
    description: "装着すると自分が世界で一番かわいいと確信できるピアス。鏡を見るたびにキラキラエフェクトが見える（幻覚）。外すと現実に引き戻されるので、外すタイミングは慎重に。左右で効果が違い、右は「かわいい」、左は「かっこいい」。",
    category: "ファッション",
    image: "diamond",
    rating: 4.6,
    reviewCount: 4567,
  },
  {
    id: "141",
    name: "他人の不幸を防ぐ傘",
    price: 8500,
    originalPrice: 12000,
    description: "差すと半径10m以内の人全員が幸せになる傘。自分には効果なし。他人の幸せを見て幸せになる上級者向けアイテム。雨の日に使うと虹が見える追加効果あり。晴れの日に使うと不審者に見える。",
    category: "ファッション",
    image: "umbrella",
    rating: 3.7,
    reviewCount: 2345,
  },
  {
    id: "142",
    name: "デッドライン可視化時計",
    price: 28000,
    originalPrice: 39000,
    description: "締め切りまでの残り時間が腕の上にホログラムで表示される時計。残り1時間を切ると時計が赤く点滅し、心拍数も上昇。最も恐ろしいのは「もう過ぎてます」の表示。上司へのCC機能はOFF推奨。",
    category: "ファッション",
    image: "watch",
    rating: 4.4,
    reviewCount: 5678,
    badge: "カウカウ's Choice",
  },
  {
    id: "143",
    name: "体重マイナス5kg軽量ダウンジャケット",
    price: 42000,
    originalPrice: 58000,
    description: "着るだけで体感体重がマイナス5kgになるダウンジャケット。階段を駆け上がれるようになるが、体重計の数字は変わらない。羽毛ではなく「希望」が詰まっている。洗濯すると希望が流れ出るので手洗い推奨。",
    category: "ファッション",
    image: "feather",
    rating: 3.9,
    reviewCount: 1234,
  },
  {
    id: "144",
    name: "中身が勝手に整理されるバッグ",
    price: 18500,
    originalPrice: 25000,
    description: "中に物を投げ入れると自動で整理整頓されるスマートバッグ。レシート・リップ・鍵がいつでも即座に取り出せる。ただしAIの整理基準が独特で、ガムと通帳が同じポケットに入っていることがある。",
    category: "ファッション",
    image: "shopping-bag",
    rating: 4.5,
    reviewCount: 6789,
  },
  {
    id: "145",
    name: "人の心が読めるサングラス",
    price: 35000,
    originalPrice: 48000,
    description: "装着すると相手の頭上に本音がテロップで表示されるサングラス。デートで「楽しい」と言いながら「早く帰りたい」のテロップが見えた時の絶望感。使わない方が幸せかもしれない。返品率No.1。",
    category: "ファッション",
    image: "glasses",
    rating: 3.3,
    reviewCount: 12345,
  },
  {
    id: "146",
    name: "自動髪切りヘアバンド",
    price: 15800,
    originalPrice: 22000,
    description: "装着すると理想の髪型にカットしてくれるヘアバンド。AI搭載で顔の形に合った髪型を提案。ただし流行を追いすぎて時々奇抜なスタイルを提案してくる。「おまかせ」は覚悟が必要。美容院代は浮くが勇気は必要。",
    category: "ファッション",
    image: "scissors",
    rating: 3.8,
    reviewCount: 4567,
  },
  {
    id: "147",
    name: "主人公オーラ発光ジャケット",
    price: 29800,
    originalPrice: 42000,
    description: "着ると背景にスポットライトが当たり、主人公のオーラが出るジャケット。風がないのに髪がなびくエフェクト付き。通行人がモブに見えるようになる。脱ぐと急にモブに戻るギャップが激しい。",
    category: "ファッション",
    image: "star",
    rating: 4.3,
    reviewCount: 3456,
  },
  {
    id: "148",
    name: "一歩で100m移動する靴",
    price: 52000,
    originalPrice: 72000,
    description: "一歩踏み出すと100m先にワープする靴。通勤が3歩で終わる。ただし着地点が選べないので壁の中に出現するリスクあり。室内では絶対に使わないでください。マラソン大会での使用は失格。",
    category: "ファッション",
    image: "footprints",
    rating: 4.1,
    reviewCount: 987,
    badge: "限定品",
  },
  {
    id: "149",
    name: "気分で色が変わるマニキュア",
    price: 3200,
    originalPrice: 4500,
    description: "感情に応じて色が変化するマニキュア。嬉しい時はピンク、怒ると赤、眠い時は紫。会議中に爪がレインボーになったら「退屈」のサイン。上司に気づかれるとまずいので、冬は手袋着用推奨。",
    category: "ファッション",
    image: "palette",
    rating: 4.4,
    reviewCount: 8901,
  },
  {
    id: "150",
    name: "絶対に忘れないパスワード生体認証ベルト",
    price: 16800,
    originalPrice: 23000,
    description: "ベルトのバックルが全デバイスのパスワードを管理する生体認証デバイス。お腹に巻くと腹筋の振動パターンで認証。太ると認証パターンが変わるのでダイエット効果もある。食べ過ぎるとログインできなくなる。",
    category: "ファッション",
    image: "lock",
    rating: 4.0,
    reviewCount: 2345,
  },
  {
    id: "151",
    name: "なくしたものが見つかるブレスレット",
    price: 9800,
    originalPrice: 14000,
    description: "なくした物の場所を腕のバイブレーションで教えてくれるブレスレット。「リモコン→ソファの隙間」「やる気→見つかりません」。探し物の95%はソファの隙間にあることが判明（当社調べ）。",
    category: "ファッション",
    image: "key",
    rating: 4.7,
    reviewCount: 7654,
    badge: "カウカウ's Choice",
  },
  {
    id: "152",
    name: "花粉完全ブロックマスクドレス",
    price: 38000,
    originalPrice: 52000,
    description: "全身を覆う花粉防御ドレス。見た目はエレガントだが防護服レベルの花粉ブロック性能。春のお花見に着ていくと注目の的。花粉症仲間から羨望の眼差しを浴びる。秋バージョンもあり。",
    category: "ファッション",
    image: "shield",
    rating: 4.2,
    reviewCount: 1890,
  },
  {
    id: "153",
    name: "そよ風を纏えるストール",
    price: 19800,
    originalPrice: 28000,
    description: "巻くと常にそよ風が吹き続けるストール。夏は涼しく、冬は...寒い。風量調節不可。常にスローモーション撮影のような髪のなびきが手に入る。ロマンチックな雰囲気演出に最適。帽子が飛ぶのは仕様。",
    category: "ファッション",
    image: "wind",
    rating: 3.5,
    reviewCount: 3456,
  },
  {
    id: "154",
    name: "氷点下ファッション冷却マフラー",
    price: 7500,
    originalPrice: 10500,
    description: "巻くだけで体温が3度下がる冷却マフラー。真夏の通勤で効果を発揮。冷えすぎて冬みたいになるので、真冬の使用は凍傷の危険あり。見た目は普通のカシミヤ風。冷凍庫に入れると永久に冷たい。",
    category: "ファッション",
    image: "snowflake",
    rating: 4.0,
    reviewCount: 5678,
  },
  {
    id: "155",
    name: "食べるとIQが10上がるクッキー",
    price: 2980,
    originalPrice: 4200,
    description: "1枚食べるとIQが10ポイント上昇するクッキー。3枚で東大レベル、5枚でアインシュタインレベルに。ただし効果は食べた後30分のみ。テスト前に大量摂食する学生が続出し、大学付近の店舗は品切れ状態。",
    category: "食品・グルメ",
    image: "cookie",
    rating: 4.5,
    reviewCount: 15678,
    badge: "ベストセラー",
  },
  {
    id: "156",
    name: "食べたら若返るケーキ",
    price: 5800,
    originalPrice: 8200,
    description: "一口食べると見た目年齢が1歳若返るケーキ。ホール全部食べると赤ちゃんに戻ってしまうので注意。味はイチゴショート。誕生日ケーキとして人気だが、ロウソクの数と若返る年数が矛盾する。",
    category: "食品・グルメ",
    image: "cake",
    rating: 4.3,
    reviewCount: 6789,
  },
  {
    id: "157",
    name: "食べても太らないピザ",
    price: 3200,
    originalPrice: 4500,
    description: "カロリーが物理的に存在しないピザ。味は完璧なのに栄養価ゼロ。ダイエット中の救世主だが、食べすぎるとカロリー不足で逆に倒れる。チーズは本物の3倍伸びる。食べた気になるが全く腹が膨れない。",
    category: "食品・グルメ",
    image: "pizza",
    rating: 4.8,
    reviewCount: 19876,
    badge: "ベストセラー",
  },
  {
    id: "158",
    name: "飲むと5分で目が覚めるコーヒー",
    price: 980,
    originalPrice: 1500,
    description: "一口飲むと目が冴えすぎて3日間眠れなくなるコーヒー。カフェイン濃度は通常の500倍。締め切り前のエンジニアに爆売れ中。飲みすぎると時間が遅く感じる副作用あり。牛乳で割ってもダメ。",
    category: "食品・グルメ",
    image: "coffee",
    rating: 4.1,
    reviewCount: 12345,
  },
  {
    id: "159",
    name: "飲んだ翌日も元気なビール",
    price: 1500,
    originalPrice: 2200,
    description: "どれだけ飲んでも二日酔いにならないビール。肝臓がサンキューと言う。味はクラフトビール級で、6缶セット。ただし記憶だけは飛ぶので翌朝のSNS投稿チェックは必須。「楽しい記憶」だけ残るフィルター付き。",
    category: "食品・グルメ",
    image: "beer",
    rating: 4.6,
    reviewCount: 8765,
  },
  {
    id: "160",
    name: "食べると願いが叶うリンゴ",
    price: 1980,
    originalPrice: 2800,
    description: "食べながら願い事をすると叶う確率が0.3%上がるリンゴ。普通のリンゴと味は同じ。叶った人のレビュー多数（ただし願い事が「リンゴを食べたい」だった可能性も）。1日1個で医者いらず効果もあり。",
    category: "食品・グルメ",
    image: "apple",
    rating: 3.5,
    reviewCount: 4567,
  },
  {
    id: "161",
    name: "陸で泳げる刺身セット",
    price: 8900,
    originalPrice: 12500,
    description: "食べると魚のように水中で呼吸できるようになる刺身。効果は1時間。マグロを食べると泳ぐスピードUP、サーモンを食べると川を遡る衝動に駆られる。フグは...覚悟して食べてください。",
    category: "食品・グルメ",
    image: "fish",
    rating: 4.2,
    reviewCount: 2345,
  },
  {
    id: "162",
    name: "恋が実るサクランボ",
    price: 3500,
    originalPrice: 4800,
    description: "2人で1つのサクランボを食べると恋が成就するサクランボ。成功率78%（当社調べ）。1人で食べると自己愛が高まる副作用あり。茎を舌で結べたらボーナスステージ突入。賞味期限は恋の期限と同じ。",
    category: "食品・グルメ",
    image: "cherry",
    rating: 4.4,
    reviewCount: 9876,
  },
  {
    id: "163",
    name: "飲むほど頭が良くなるワイン",
    price: 12800,
    originalPrice: 18000,
    description: "飲むほどIQが上がるワイン。1杯で哲学者、2杯で科学者、3杯で支離滅裂。4杯目以降は普通のワインと同じ効果（酔っ払い）。ソムリエAIが最適な飲酒ペースを提案。フルボディで芳醇。",
    category: "食品・グルメ",
    image: "wine",
    rating: 4.0,
    reviewCount: 3456,
    badge: "限定品",
  },
  {
    id: "164",
    name: "永遠に炭酸が抜けないジュース",
    price: 680,
    originalPrice: 980,
    description: "開封後100年経っても炭酸が抜けないジュース。量子泡技術により炭酸が永久固定。ただし振ったら爆発する点は通常の炭酸と同じ。冷蔵庫に入れ忘れても炭酸は抜けないが、味は落ちる。",
    category: "食品・グルメ",
    image: "cup-soda",
    rating: 4.7,
    reviewCount: 7654,
  },
  {
    id: "165",
    name: "食べても虫歯にならないキャンディ",
    price: 500,
    originalPrice: 780,
    description: "食べると歯が逆にきれいになるキャンディ。歯医者が廃業を恐れて反対運動中。味は30種類。1日100個食べても大丈夫（歯科的には。糖尿病的には自己責任）。歯磨き粉味が意外と人気。",
    category: "食品・グルメ",
    image: "candy",
    rating: 4.5,
    reviewCount: 18765,
  },
  {
    id: "166",
    name: "激辛なのに辛くない唐辛子",
    price: 1200,
    originalPrice: 1800,
    description: "見た目はデスソース級の赤さだが、味は甘い唐辛子。辛いもの好きアピールしたいけど実は苦手な人に最適。InstagramやTikTokでの「激辛チャレンジ」で涼しい顔ができる。種を植えても甘い実がなる。",
    category: "食品・グルメ",
    image: "flame",
    rating: 3.9,
    reviewCount: 5432,
  },
  {
    id: "167",
    name: "光合成で育つインスタント盆栽",
    price: 4800,
    originalPrice: 6500,
    description: "水やり不要、光を当てるだけで育つインスタント盆栽。日曜日に植えて月曜日に立派な盆栽が完成。四季を1週間で体験でき、紅葉も楽しめる。枯れたら電子レンジで復活する手軽さ。ミニサイズ。",
    category: "食品・グルメ",
    image: "leaf",
    rating: 4.3,
    reviewCount: 3456,
  },
  {
    id: "168",
    name: "座ると寝落ちするソファ",
    price: 78000,
    originalPrice: 110000,
    description: "座った瞬間に深い眠りに落ちるソファ。睡眠の質は最高級ベッドの3倍。問題は座ったら最後、8時間起きられないこと。来客用に置くと客が帰らなくなる。リモートワーク中の使用は自己責任。",
    category: "ホーム・生活",
    image: "sofa",
    rating: 4.8,
    reviewCount: 2345,
    badge: "カウカウ's Choice",
  },
  {
    id: "169",
    name: "寝ている間に勉強してくれるベッド",
    price: 98000,
    originalPrice: 138000,
    description: "寝ている間にAIが脳に直接知識をインストールするベッド。起きたらTOEIC満点レベルの英語力が身についている（予定）。実際は起きた時に「なんか賢くなった気がする」程度。寝心地は最高。",
    category: "ホーム・生活",
    image: "bed-double",
    rating: 4.1,
    reviewCount: 4567,
  },
  {
    id: "170",
    name: "部屋の空気を読むスタンドライト",
    price: 15800,
    originalPrice: 22000,
    description: "部屋の空気（雰囲気）を読んでライティングを自動調整するライト。ケンカ中は暖色でムードを和らげ、勉強中は集中できる白色に。「修羅場」を検知すると消灯して見なかったことにする機能あり。",
    category: "ホーム・生活",
    image: "lamp",
    rating: 4.4,
    reviewCount: 3456,
  },
  {
    id: "171",
    name: "話しかけると涼しくなる扇風機",
    price: 12800,
    originalPrice: 18000,
    description: "「暑い」と言うと風量UP、「寒い」と言うと風量DOWNする音声認識扇風機。「ちょうどいい」を覚えてくれるAI搭載。独り言が多い人は風が安定しない。隣の部屋の声にも反応するのが玉に瑕。",
    category: "ホーム・生活",
    image: "fan",
    rating: 4.2,
    reviewCount: 6789,
  },
  {
    id: "172",
    name: "来客を勝手に帰らせるドアベル",
    price: 8900,
    originalPrice: 12500,
    description: "長居する来客を自然に帰らせるスマートドアベル。滞在2時間を超えると「そろそろ電車がなくなりますよ」と優しく通知。NHK集金には「留守です」と自動応答。友達が減る可能性あり。",
    category: "ホーム・生活",
    image: "bell",
    rating: 4.6,
    reviewCount: 8901,
    badge: "お買い得",
  },
  {
    id: "173",
    name: "壊れる前に直す予知工具セット",
    price: 25000,
    originalPrice: 35000,
    description: "家電が壊れる3日前に通知してくれて、自動で修理を手配する工具セット。「冷蔵庫があと72時間で寿命です」とLINEが来る。予知精度99%。ただし人間関係の修理は対象外。予知結果は変えられない。",
    category: "ホーム・生活",
    image: "wrench",
    rating: 4.3,
    reviewCount: 2345,
  },
  {
    id: "174",
    name: "絶対に的中する天気予報花瓶",
    price: 6800,
    originalPrice: 9500,
    description: "挿した花の咲き方で明日の天気が100%分かる花瓶。バラが開けば晴れ、チューリップが閉じれば雨。台風の時は花が回転する。天気予報士より正確だが、花代が毎月かかるのがデメリット。",
    category: "ホーム・生活",
    image: "target",
    rating: 4.5,
    reviewCount: 5678,
  },
  {
    id: "175",
    name: "全自動言い訳家事ロボット",
    price: 65000,
    originalPrice: 90000,
    description: "家事をサボった時に「やろうとしてたんだけど...」と完璧な言い訳を考えてくれるロボット。たまに本当に家事もしてくれる。しないことの方が多い。人間のダメな部分をAIが学習した結果生まれた製品。",
    category: "ホーム・生活",
    image: "cog",
    rating: 3.8,
    reviewCount: 4567,
  },
  {
    id: "176",
    name: "二度寝防止爆音目覚まし",
    price: 4500,
    originalPrice: 6200,
    description: "スヌーズを押すと音量が2倍になる目覚まし。3回スヌーズで近所迷惑レベル、5回で消防車が来るレベル。物理的に起きざるを得ない。叩いて壊そうとすると「壊さないで」と泣く機能搭載。",
    category: "ホーム・生活",
    image: "alarm-clock",
    rating: 4.0,
    reviewCount: 11234,
  },
  {
    id: "177",
    name: "汚れが勝手に消える魔法のモップ",
    price: 11000,
    originalPrice: 15800,
    description: "床に置いておくだけで夜中に勝手に掃除してくれるモップ。朝起きるとピカピカ。動いている姿は誰も見たことがない。監視カメラにも映らない。掃除の妖精が宿っているとかいないとか。",
    category: "ホーム・生活",
    image: "wand-2",
    rating: 4.7,
    reviewCount: 7890,
    badge: "お買い得",
  },
  {
    id: "178",
    name: "散歩が楽しくなる犬用翻訳首輪",
    price: 14800,
    originalPrice: 20000,
    description: "犬の気持ちを翻訳して飼い主のスマホに表示する首輪。散歩中の犬の感想は90%が「この匂い最高」。他の犬を見た時の翻訳は「あいつ弱そう」か「あいつ強そう」の二択。猫への使用は「無視」が表示され続ける。",
    category: "ホーム・生活",
    image: "dog",
    rating: 4.6,
    reviewCount: 9876,
  },
  {
    id: "179",
    name: "猫の機嫌予報カレンダー",
    price: 3980,
    originalPrice: 5500,
    description: "猫の機嫌を1週間先まで予報するカレンダー。「月曜：触っても大丈夫」「火曜：近づくと引っかかれる」が分かる。的中率は50%（猫は気まぐれなため）。猫が予報を見て逆の行動を取ることもある。",
    category: "ホーム・生活",
    image: "cat",
    rating: 4.3,
    reviewCount: 13456,
  },
  {
    id: "180",
    name: "部屋に富士山を出現させる加湿器",
    price: 22000,
    originalPrice: 30000,
    description: "ミストで部屋にミニ富士山を再現する加湿器。朝はご来光、夕方は夕焼けモード。雲海も再現可能で、リビングが天空の城になる。加湿能力は普通。登山家に「これじゃない」と言われがち。",
    category: "ホーム・生活",
    image: "mountain",
    rating: 4.1,
    reviewCount: 2345,
  },
  {
    id: "181",
    name: "開けたら何も入ってないサプライズ箱",
    price: 5980,
    originalPrice: 8500,
    description: "開けると「何もないことの素晴らしさ」を説く哲学AIが起動するギフト箱。禅の心を学べる。贈り物としてはリスクが高いが、「物欲からの解放」をテーマにした自分へのプレゼントとして人気。買うこと自体が矛盾。",
    category: "ホーム・生活",
    image: "gift",
    rating: 3.2,
    reviewCount: 6789,
  },
  {
    id: "182",
    name: "日焼けしないのに小麦肌になるライト",
    price: 18500,
    originalPrice: 25000,
    description: "紫外線ゼロで健康的な小麦肌になれるライト。シミもシワもできない夢の日焼け。「海行ったの？」と聞かれるが実際はリビングで浴びただけ。色白に戻りたい場合は「リセットモード」で3日で元通り。",
    category: "ヘルス・ビューティー",
    image: "sun",
    rating: 4.4,
    reviewCount: 5678,
  },
  {
    id: "183",
    name: "体温で天気予報する体温計",
    price: 2980,
    originalPrice: 4200,
    description: "体温を測ると明日の天気も同時に表示される体温計。体温36.5度で晴れ、37.0度で曇り、38.0度以上で嵐。体調と天気の相関関係をAIが分析。花粉飛散量も表示。風邪と天気、どっちが心配？",
    category: "ヘルス・ビューティー",
    image: "thermometer",
    rating: 3.6,
    reviewCount: 3456,
  },
  {
    id: "184",
    name: "失恋を3秒で治す絆創膏",
    price: 1500,
    originalPrice: 2200,
    description: "胸に貼ると失恋の痛みが3秒で消える絆創膏。ハート型で可愛い。ただし記憶は消えないので、痛みだけなくなって思い出はクリアに残る。それが辛いという声も。リピーターが多い（恋多き人向け）。",
    category: "ヘルス・ビューティー",
    image: "heart",
    rating: 4.2,
    reviewCount: 14567,
  },
  {
    id: "185",
    name: "塗るだけで肌がツヤツヤになるラメクリーム",
    price: 4200,
    originalPrice: 5800,
    description: "塗った瞬間から肌がアイドル級のツヤを放つクリーム。ラメの量は3段階調整可能。最大レベルだとディスコボールになるので注意。光の加減で相手が目をつぶるほど輝く。夜道で車のヘッドライトに反射して安全。",
    category: "ヘルス・ビューティー",
    image: "sparkles",
    rating: 4.5,
    reviewCount: 8901,
  },
  {
    id: "186",
    name: "涙が美容液になるアイドロップ",
    price: 6800,
    originalPrice: 9500,
    description: "泣くほどに肌がきれいになるアイドロップ。悲しい映画を見ながらスキンケアが完了する画期的商品。玉ねぎを切る時の涙でも効果あり。号泣すると翌日はエステ帰りの肌に。泣ける映画リスト付き。",
    category: "ヘルス・ビューティー",
    image: "droplets",
    rating: 4.3,
    reviewCount: 4567,
  },
  {
    id: "187",
    name: "飲むと身長が3cm伸びるサプリ",
    price: 8900,
    originalPrice: 12800,
    description: "飲むと一時的に身長が3cm伸びるサプリ。効果は8時間。合コンやお見合い前に飲む人が続出。ただし足から伸びるので靴のサイズが合わなくなる副作用あり。2錠同時に飲むと6cm伸びるが膝が痛い。",
    category: "ヘルス・ビューティー",
    image: "pill",
    rating: 3.8,
    reviewCount: 12345,
  },
  {
    id: "188",
    name: "視力が5.0になる目薬",
    price: 3500,
    originalPrice: 4800,
    description: "さすと24時間だけ視力が5.0になる目薬。遠くの看板も裸眼で読める。鳥の表情まで見える。見えすぎて知りたくなかったものまで見えるのがデメリット。細菌が見えるようになると外食ができなくなる。",
    category: "ヘルス・ビューティー",
    image: "eye",
    rating: 4.1,
    reviewCount: 7890,
  },
  {
    id: "189",
    name: "香りで性格が変わるアロマオイル",
    price: 5200,
    originalPrice: 7200,
    description: "嗅ぐ香りによって性格が一時的に変わるアロマオイル。ローズは社交的に、ラベンダーは穏やかに、ミントは攻撃的に。プレゼン前はシトラスで自信満々モードに。混ぜると多重人格になるので厳禁。",
    category: "ヘルス・ビューティー",
    image: "flower-2",
    rating: 4.0,
    reviewCount: 5432,
  },
  {
    id: "190",
    name: "細胞が歌い出すボディソープ",
    price: 2200,
    originalPrice: 3200,
    description: "使うと細胞レベルで喜んで歌い出すボディソープ。顕微鏡で見ると細胞が合唱している（イメージ映像）。肌のターンオーバーが促進され、全身すべすべに。歌は「情熱大陸」のテーマが人気。",
    category: "ヘルス・ビューティー",
    image: "microscope",
    rating: 4.4,
    reviewCount: 6789,
  },
  {
    id: "191",
    name: "塗ると夢見心地になるナイトクリーム",
    price: 7500,
    originalPrice: 10500,
    description: "塗ると幸せな夢が100%見られるナイトクリーム。夢の中で推しに会える確率80%。残り20%は焼肉の夢。朝起きた時の幸福感が1日持続する。ただし現実がつらく感じるようになる副作用が報告されている。",
    category: "ヘルス・ビューティー",
    image: "moon",
    rating: 4.6,
    reviewCount: 3456,
    badge: "新着",
  },
  {
    id: "192",
    name: "方向音痴が治るサプリ",
    price: 2800,
    originalPrice: 3900,
    description: "飲むと体内コンパスが起動して方向音痴が治るサプリ。北が分かるようになる。ただし方角が分かっても地名は分からないので結局迷う。渡り鳥と同じ磁気感知機能搭載。鉄塔の近くでは誤作動する。",
    category: "ヘルス・ビューティー",
    image: "compass",
    rating: 3.4,
    reviewCount: 8765,
  },
  {
    id: "193",
    name: "漕ぐと時間が巻き戻る自転車",
    price: 55000,
    originalPrice: 78000,
    description: "ペダルを逆回転させると時間が1分巻き戻る自転車。「あの信号、間に合ったのに」を解消。ただし巻き戻すと体力も元に戻るので永遠に漕ぎ続けることになる。前に進むと未来が見える機能は開発中。",
    category: "エンタメ・趣味",
    image: "bike",
    rating: 4.3,
    reviewCount: 2345,
  },
  {
    id: "194",
    name: "鳥と友達になれるイヤホン",
    price: 7800,
    originalPrice: 11000,
    description: "装着すると鳥のさえずりが会話に聞こえるイヤホン。スズメは意外と毒舌、ハトは平和主義、カラスはインテリ。鳥たちの井戸端会議が聞こえるようになる。カラスのゴシップが一番面白い。",
    category: "エンタメ・趣味",
    image: "bird",
    rating: 4.5,
    reviewCount: 4567,
  },
  {
    id: "195",
    name: "虫と交渉できるスプレー",
    price: 1980,
    originalPrice: 2800,
    description: "虫に「出て行ってください」と丁寧にお願いできるスプレー。殺虫ではなく交渉による平和的解決。ゴキブリの場合、交渉成功率は30%。失敗すると逆に居座られる。蚊には「血を吸わない契約書」にサインさせる。",
    category: "エンタメ・趣味",
    image: "bug",
    rating: 3.7,
    reviewCount: 15678,
  },
  {
    id: "196",
    name: "弾かなくても上手く聞こえるギターピック",
    price: 2400,
    originalPrice: 3500,
    description: "このピックでギターを弾くと、どんなに下手でもプロの演奏に聞こえるピック。コード知らなくても適当に弾けばいい曲になる。路上ライブで使うと投げ銭が集まる。アンプラグドだとバレるので注意。",
    category: "エンタメ・趣味",
    image: "guitar",
    rating: 4.2,
    reviewCount: 6789,
  },
  {
    id: "197",
    name: "じゃんけん必勝グローブ",
    price: 6500,
    originalPrice: 9000,
    description: "相手が出す手を0.3秒前に予測して勝つグローブ。じゃんけんで負けなくなるが、友達をなくす。大会で使うとバレるので日常使い推奨。あいこの場合は高速で手を変えるアシスト機能搭載。",
    category: "エンタメ・趣味",
    image: "trophy",
    rating: 4.4,
    reviewCount: 5432,
    badge: "お買い得",
  },
  {
    id: "198",
    name: "渋滞を避ける予知カーナビ",
    price: 42000,
    originalPrice: 58000,
    description: "1時間後の渋滞を予知して完璧に回避するカーナビ。渋滞に巻き込まれる確率ゼロ。ただし最短ルートが「田んぼのあぜ道」を案内することがある。景色は楽しめるが車は汚れる。洗車代は別途。",
    category: "エンタメ・趣味",
    image: "car",
    rating: 4.1,
    reviewCount: 3456,
  },
  {
    id: "199",
    name: "グランピング全自動設営テント",
    price: 88000,
    originalPrice: 125000,
    description: "ボタン一つでグランピング環境が完成するテント。シャンデリア、ベッド、ミニバーまで自動展開。隣のキャンパーが泣く豪華さ。たたむのは手動で3時間かかる。設営1秒、撤収180分。",
    category: "エンタメ・趣味",
    image: "tent",
    rating: 4.8,
    reviewCount: 987,
    badge: "新着",
  },
  {
    id: "200",
    name: "カラオケ採点が全部100点になるアプリ専用マイク",
    price: 9800,
    originalPrice: 14000,
    description: "このマイクを使うとカラオケの採点が物理的に100点になるマイク。音痴でも100点。ただし周りの人の耳は誤魔化せない。「点数は高いのに...」という新しいジャンルの音痴が誕生。忘年会で大活躍。",
    category: "エンタメ・趣味",
    image: "music",
    rating: 4.5,
    reviewCount: 11234,
  },
  {
    id: "201",
    name: "ガチャガチャ運が良くなるコイン",
    price: 980,
    originalPrice: 1500,
    description: "このコインでガチャガチャを回すと必ずレアが出る。ただし「レア」の定義はガチャ側の判断。自分が欲しいものが出るとは限らない。コイン自体がレアなので、このコインをガチャで当てるのが最難関。",
    category: "エンタメ・趣味",
    image: "circle",
    rating: 3.9,
    reviewCount: 19876,
  },
  {
    id: "202",
    name: "書くだけで小説が完成するペン",
    price: 15800,
    originalPrice: 22000,
    description: "最初の一文を書くと残りをAIが自動で書き上げるペン。文学賞受賞レベルの文章力。ただし全作品が「それは、ある雨の日のことだった」で始まる。ジャンル指定は可能だが、必ず恋愛要素が入る。",
    category: "エンタメ・趣味",
    image: "pen-tool",
    rating: 4.0,
    reviewCount: 4567,
  },
  {
    id: "203",
    name: "ラジオ体操で筋肉ムキムキになるラジオ",
    price: 8500,
    originalPrice: 12000,
    description: "このラジオから流れるラジオ体操をすると、通常の100倍の運動効果があるラジオ。第一だけでジム3時間分。第二まで行くとボディビルダー級に。ただし筋肉痛も100倍なので翌日は動けない。",
    category: "エンタメ・趣味",
    image: "radio",
    rating: 4.3,
    reviewCount: 7890,
  },
  {
    id: "204",
    name: "聴くと性格が良くなるヘッドフォン",
    price: 24800,
    originalPrice: 35000,
    description: "装着すると優しい気持ちになれるヘッドフォン。世界平和を願うようになり、席を譲り、ゴミを拾い、全員に挨拶する。外すと元の性格に戻る。使い続けると本当に性格が良くなるらしい（個人の感想）。",
    category: "エンタメ・趣味",
    image: "headphones",
    rating: 4.6,
    reviewCount: 3456,
  },
  {
    id: "205",
    name: "打ち上げると願いが叶うミニ花火",
    price: 3200,
    originalPrice: 4500,
    description: "打ち上げた瞬間に願い事をすると叶う確率が2%上がるミニ花火。室内用で火を使わないLED花火。音も「ドーン（スピーカー再生）」で安全。願い事の内容によって花火の色が変わる。「お金」は緑色。",
    category: "エンタメ・趣味",
    image: "rocket",
    rating: 3.8,
    reviewCount: 8765,
  },
  {
    id: "206",
    name: "記憶力が10倍になるハチマキ",
    price: 11000,
    originalPrice: 15800,
    description: "巻くと記憶力が10倍になるハチマキ。受験生の必需品。ただし忘れたい記憶も10倍鮮明に蘇るのがデメリット。黒歴史が4K画質で再生される。試験が終わったら速やかに外すことを推奨。",
    category: "エンタメ・趣味",
    image: "brain",
    rating: 4.2,
    reviewCount: 6543,
    badge: "お買い得",
  },
  {
    id: "207",
    name: "ゲームの世界に5分だけ入れるVRゴーグル",
    price: 78000,
    originalPrice: 110000,
    description: "ゲームの世界に物理的に入れるVRゴーグル。5分間だけゲーム内で冒険できる。敵に倒されると現実世界に強制送還。ゲーム内で手に入れたアイテムは持ち帰れない。楽しいが虚しくなる。",
    category: "エンタメ・趣味",
    image: "gamepad-2",
    rating: 4.7,
    reviewCount: 2345,
    badge: "限定品",
  },
  {
    id: "208",
    name: "写真を撮ると10年後の自分が映るスマホフィルター",
    price: 1980,
    originalPrice: 2800,
    description: "自撮りすると10年後の自分の顔が映るスマホフィルター。健康的な生活をしていると若々しい姿に。不摂生だと衝撃の未来が。ダイエットのモチベーションに最適だが、見たくない人は見ない方がいい。",
    category: "テクノロジー",
    image: "smartphone",
    rating: 3.5,
    reviewCount: 18765,
  },
  {
    id: "209",
    name: "被ると王様扱いされるハット",
    price: 35000,
    originalPrice: 48000,
    description: "被ると周囲の人が無意識に敬語で話しかけてくるハット。コンビニ店員も「かしこまりました、陛下」と対応。脱ぐと急に「お客様、レジ袋いりますか？」に戻る。権力の味を知ると脱げなくなる。",
    category: "ファッション",
    image: "crown",
    rating: 4.3,
    reviewCount: 1234,
  },
  {
    id: "210",
    name: "光る宝石風イヤリング",
    price: 19800,
    originalPrice: 28000,
    description: "暗闇で本物のダイヤモンド以上に輝くLEDイヤリング。パーティーで注目の的になれる。充電式で8時間持続。光量MAXにすると読書灯としても使えるが、まぶしすぎて周りから苦情が来る。",
    category: "ファッション",
    image: "diamond",
    rating: 4.1,
    reviewCount: 5678,
  },
  {
    id: "211",
    name: "飲むと方言が出るコーヒー",
    price: 780,
    originalPrice: 1200,
    description: "飲むと無意識に方言で話し始めるコーヒー。フレーバーで方言が変わる。モカは関西弁、ブルーマウンテンは東北弁、エスプレッソは博多弁。外国人が飲むと日本語の方言で話し始める不思議仕様。",
    category: "食品・グルメ",
    image: "coffee",
    rating: 4.4,
    reviewCount: 9876,
    badge: "新着",
  },
  {
    id: "212",
    name: "食べると正直になるピザまん",
    price: 580,
    originalPrice: 880,
    description: "食べると2時間だけ嘘がつけなくなるピザまん。合コンで出すと本音トークが止まらない。「好きなタイプは？」に正直に答えてしまう。ビジネスシーンでの使用は大惨事を招く可能性あり。美味しい。",
    category: "食品・グルメ",
    image: "pizza",
    rating: 4.0,
    reviewCount: 7654,
  },
  {
    id: "213",
    name: "座ると運気が上がるクッション",
    price: 9800,
    originalPrice: 14000,
    description: "座るだけで運気が上昇するクッション。宝くじの当選確率は変わらないが、小さなラッキーが増える。エレベーターが待たずに来る、自販機でもう1本出てくるなど。座り心地は普通。風水師監修。",
    category: "ホーム・生活",
    image: "sofa",
    rating: 3.9,
    reviewCount: 8901,
  },
  {
    id: "214",
    name: "読書スピードが10倍になるデスクライト",
    price: 16800,
    originalPrice: 23000,
    description: "この光の下で本を読むと読書スピードが10倍になるデスクライト。ただし速すぎて内容が頭に入らない。再読が必要になるので結局同じ時間がかかる。積読解消には使える。目は疲れない設計。",
    category: "ホーム・生活",
    image: "lamp",
    rating: 3.6,
    reviewCount: 4567,
  },
  {
    id: "215",
    name: "飲むと共感力MAXになるドリンク",
    price: 1800,
    originalPrice: 2500,
    description: "飲むと他人の感情が手に取るように分かるドリンク。友達の相談に的確なアドバイスができるようになる。ただし満員電車で飲むと全員の感情が流れ込んで情報過多で倒れる。1日1本まで。",
    category: "ヘルス・ビューティー",
    image: "heart",
    rating: 4.2,
    reviewCount: 6543,
  },
  {
    id: "216",
    name: "オーラが目に見えるコンタクトレンズ",
    price: 28000,
    originalPrice: 39000,
    description: "装着すると人のオーラがキラキラ見えるコンタクトレンズ。良い人は金色、疲れてる人は灰色、推しは虹色に見える。自分のオーラも鏡で確認可能。月曜朝の通勤電車は灰色だらけで景色が暗い。",
    category: "ヘルス・ビューティー",
    image: "sparkles",
    rating: 4.5,
    reviewCount: 3456,
    badge: "限定品",
  },
  {
    id: "217",
    name: "運勢を書き換えるおみくじ",
    price: 2400,
    originalPrice: 3500,
    description: "引いた後に「大吉」に書き換えられるおみくじ。結果に不満がある時にペンで上書きすると現実が書き換わる（気がする）。「凶」を「大凶」に書き換える強者もいる。年間100万枚販売の実績。",
    category: "エンタメ・趣味",
    image: "star",
    rating: 4.0,
    reviewCount: 20000,
  },
  {
    id: "218",
    name: "もらった人が絶対に喜ぶギフトカード",
    price: 5000,
    originalPrice: 7000,
    description: "贈られた人の脳に直接「嬉しい」信号を送るギフトカード。金額に関係なく幸福度MAX。実際の中身は感謝のメッセージだけだが、受け取った瞬間に涙が出るほど感動する。お歳暮、お中元に最適。原価は紙代のみ。",
    category: "エンタメ・趣味",
    image: "gift",
    rating: 4.8,
    reviewCount: 11234,
    badge: "お買い得",
  },
];
